extern "C" __attribute__((noinline)) unsigned f0(unsigned x){return (x*7u)^0u;}
extern "C" __attribute__((noinline)) unsigned f1(unsigned x){return (x*7u)^1u;}
extern "C" __attribute__((noinline)) unsigned f2(unsigned x){return (x*7u)^2u;}
extern "C" __attribute__((noinline)) unsigned f3(unsigned x){return (x*7u)^3u;}
extern "C" __attribute__((noinline)) unsigned f4(unsigned x){return (x*7u)^4u;}
extern "C" __attribute__((noinline)) unsigned f5(unsigned x){return (x*7u)^5u;}
extern "C" __attribute__((noinline)) unsigned f6(unsigned x){return (x*7u)^6u;}
extern "C" __attribute__((noinline)) unsigned f7(unsigned x){return (x*7u)^7u;}
extern "C" __attribute__((noinline)) unsigned f8(unsigned x){return (x*7u)^8u;}
extern "C" __attribute__((noinline)) unsigned f9(unsigned x){return (x*7u)^9u;}
extern "C" __attribute__((noinline)) unsigned f10(unsigned x){return (x*7u)^10u;}
extern "C" __attribute__((noinline)) unsigned f11(unsigned x){return (x*7u)^11u;}
extern "C" __attribute__((noinline)) unsigned f12(unsigned x){return (x*7u)^12u;}
extern "C" __attribute__((noinline)) unsigned f13(unsigned x){return (x*7u)^13u;}
extern "C" __attribute__((noinline)) unsigned f14(unsigned x){return (x*7u)^14u;}
extern "C" __attribute__((noinline)) unsigned f15(unsigned x){return (x*7u)^15u;}
extern "C" __attribute__((noinline)) unsigned f16(unsigned x){return (x*7u)^16u;}
extern "C" __attribute__((noinline)) unsigned f17(unsigned x){return (x*7u)^17u;}
extern "C" __attribute__((noinline)) unsigned f18(unsigned x){return (x*7u)^18u;}
extern "C" __attribute__((noinline)) unsigned f19(unsigned x){return (x*7u)^19u;}
extern "C" __attribute__((noinline)) unsigned f20(unsigned x){return (x*7u)^20u;}
extern "C" __attribute__((noinline)) unsigned f21(unsigned x){return (x*7u)^21u;}
extern "C" __attribute__((noinline)) unsigned f22(unsigned x){return (x*7u)^22u;}
extern "C" __attribute__((noinline)) unsigned f23(unsigned x){return (x*7u)^23u;}
extern "C" __attribute__((noinline)) unsigned f24(unsigned x){return (x*7u)^24u;}
extern "C" __attribute__((noinline)) unsigned f25(unsigned x){return (x*7u)^25u;}
extern "C" __attribute__((noinline)) unsigned f26(unsigned x){return (x*7u)^26u;}
extern "C" __attribute__((noinline)) unsigned f27(unsigned x){return (x*7u)^27u;}
extern "C" __attribute__((noinline)) unsigned f28(unsigned x){return (x*7u)^28u;}
extern "C" __attribute__((noinline)) unsigned f29(unsigned x){return (x*7u)^29u;}
extern "C" __attribute__((noinline)) unsigned f30(unsigned x){return (x*7u)^30u;}
extern "C" __attribute__((noinline)) unsigned f31(unsigned x){return (x*7u)^31u;}
extern "C" __attribute__((noinline)) unsigned f32(unsigned x){return (x*7u)^32u;}
extern "C" __attribute__((noinline)) unsigned f33(unsigned x){return (x*7u)^33u;}
extern "C" __attribute__((noinline)) unsigned f34(unsigned x){return (x*7u)^34u;}
extern "C" __attribute__((noinline)) unsigned f35(unsigned x){return (x*7u)^35u;}
extern "C" __attribute__((noinline)) unsigned f36(unsigned x){return (x*7u)^36u;}
extern "C" __attribute__((noinline)) unsigned f37(unsigned x){return (x*7u)^37u;}
extern "C" __attribute__((noinline)) unsigned f38(unsigned x){return (x*7u)^38u;}
extern "C" __attribute__((noinline)) unsigned f39(unsigned x){return (x*7u)^39u;}
extern "C" __attribute__((noinline)) unsigned f40(unsigned x){return (x*7u)^40u;}
extern "C" __attribute__((noinline)) unsigned f41(unsigned x){return (x*7u)^41u;}
extern "C" __attribute__((noinline)) unsigned f42(unsigned x){return (x*7u)^42u;}
extern "C" __attribute__((noinline)) unsigned f43(unsigned x){return (x*7u)^43u;}
extern "C" __attribute__((noinline)) unsigned f44(unsigned x){return (x*7u)^44u;}
extern "C" __attribute__((noinline)) unsigned f45(unsigned x){return (x*7u)^45u;}
extern "C" __attribute__((noinline)) unsigned f46(unsigned x){return (x*7u)^46u;}
extern "C" __attribute__((noinline)) unsigned f47(unsigned x){return (x*7u)^47u;}
extern "C" __attribute__((noinline)) unsigned f48(unsigned x){return (x*7u)^48u;}
extern "C" __attribute__((noinline)) unsigned f49(unsigned x){return (x*7u)^49u;}