extern "C" __attribute__((noinline)) unsigned f0(unsigned x){return (x*7u)^0u;}
extern "C" __attribute__((noinline)) unsigned f1(unsigned x){return (x*7u)^1u;}
extern "C" __attribute__((noinline)) unsigned f2(unsigned x){return (x*7u)^2u;}
extern "C" __attribute__((noinline)) unsigned f3(unsigned x){return (x*7u)^3u;}
extern "C" __attribute__((noinline)) unsigned f4(unsigned x){return (x*7u)^4u;}
extern "C" __attribute__((noinline)) unsigned f5(unsigned x){return (x*7u)^5u;}
extern "C" __attribute__((noinline)) unsigned f6(unsigned x){return (x*7u)^6u;}
extern "C" __attribute__((noinline)) unsigned f7(unsigned x){return (x*7u)^7u;}
extern "C" __attribute__((noinline)) unsigned f8(unsigned x){return (x*7u)^8u;}
extern "C" __attribute__((noinline)) unsigned f9(unsigned x){return (x*7u)^9u;}
extern "C" __attribute__((noinline)) unsigned f10(unsigned x){return (x*7u)^10u;}
extern "C" __attribute__((noinline)) unsigned f11(unsigned x){return (x*7u)^11u;}
extern "C" __attribute__((noinline)) unsigned f12(unsigned x){return (x*7u)^12u;}
extern "C" __attribute__((noinline)) unsigned f13(unsigned x){return (x*7u)^13u;}
extern "C" __attribute__((noinline)) unsigned f14(unsigned x){return (x*7u)^14u;}
extern "C" __attribute__((noinline)) unsigned f15(unsigned x){return (x*7u)^15u;}
extern "C" __attribute__((noinline)) unsigned f16(unsigned x){return (x*7u)^16u;}
extern "C" __attribute__((noinline)) unsigned f17(unsigned x){return (x*7u)^17u;}
extern "C" __attribute__((noinline)) unsigned f18(unsigned x){return (x*7u)^18u;}
extern "C" __attribute__((noinline)) unsigned f19(unsigned x){return (x*7u)^19u;}
extern "C" __attribute__((noinline)) unsigned f20(unsigned x){return (x*7u)^20u;}
extern "C" __attribute__((noinline)) unsigned f21(unsigned x){return (x*7u)^21u;}
extern "C" __attribute__((noinline)) unsigned f22(unsigned x){return (x*7u)^22u;}
extern "C" __attribute__((noinline)) unsigned f23(unsigned x){return (x*7u)^23u;}
extern "C" __attribute__((noinline)) unsigned f24(unsigned x){return (x*7u)^24u;}
extern "C" __attribute__((noinline)) unsigned f25(unsigned x){return (x*7u)^25u;}
extern "C" __attribute__((noinline)) unsigned f26(unsigned x){return (x*7u)^26u;}
extern "C" __attribute__((noinline)) unsigned f27(unsigned x){return (x*7u)^27u;}
extern "C" __attribute__((noinline)) unsigned f28(unsigned x){return (x*7u)^28u;}
extern "C" __attribute__((noinline)) unsigned f29(unsigned x){return (x*7u)^29u;}
extern "C" __attribute__((noinline)) unsigned f30(unsigned x){return (x*7u)^30u;}
extern "C" __attribute__((noinline)) unsigned f31(unsigned x){return (x*7u)^31u;}
extern "C" __attribute__((noinline)) unsigned f32(unsigned x){return (x*7u)^32u;}
extern "C" __attribute__((noinline)) unsigned f33(unsigned x){return (x*7u)^33u;}
extern "C" __attribute__((noinline)) unsigned f34(unsigned x){return (x*7u)^34u;}
extern "C" __attribute__((noinline)) unsigned f35(unsigned x){return (x*7u)^35u;}
extern "C" __attribute__((noinline)) unsigned f36(unsigned x){return (x*7u)^36u;}
extern "C" __attribute__((noinline)) unsigned f37(unsigned x){return (x*7u)^37u;}
extern "C" __attribute__((noinline)) unsigned f38(unsigned x){return (x*7u)^38u;}
extern "C" __attribute__((noinline)) unsigned f39(unsigned x){return (x*7u)^39u;}
extern "C" __attribute__((noinline)) unsigned f40(unsigned x){return (x*7u)^40u;}
extern "C" __attribute__((noinline)) unsigned f41(unsigned x){return (x*7u)^41u;}
extern "C" __attribute__((noinline)) unsigned f42(unsigned x){return (x*7u)^42u;}
extern "C" __attribute__((noinline)) unsigned f43(unsigned x){return (x*7u)^43u;}
extern "C" __attribute__((noinline)) unsigned f44(unsigned x){return (x*7u)^44u;}
extern "C" __attribute__((noinline)) unsigned f45(unsigned x){return (x*7u)^45u;}
extern "C" __attribute__((noinline)) unsigned f46(unsigned x){return (x*7u)^46u;}
extern "C" __attribute__((noinline)) unsigned f47(unsigned x){return (x*7u)^47u;}
extern "C" __attribute__((noinline)) unsigned f48(unsigned x){return (x*7u)^48u;}
extern "C" __attribute__((noinline)) unsigned f49(unsigned x){return (x*7u)^49u;}
extern "C" __attribute__((noinline)) unsigned f50(unsigned x){return (x*7u)^50u;}
extern "C" __attribute__((noinline)) unsigned f51(unsigned x){return (x*7u)^51u;}
extern "C" __attribute__((noinline)) unsigned f52(unsigned x){return (x*7u)^52u;}
extern "C" __attribute__((noinline)) unsigned f53(unsigned x){return (x*7u)^53u;}
extern "C" __attribute__((noinline)) unsigned f54(unsigned x){return (x*7u)^54u;}
extern "C" __attribute__((noinline)) unsigned f55(unsigned x){return (x*7u)^55u;}
extern "C" __attribute__((noinline)) unsigned f56(unsigned x){return (x*7u)^56u;}
extern "C" __attribute__((noinline)) unsigned f57(unsigned x){return (x*7u)^57u;}
extern "C" __attribute__((noinline)) unsigned f58(unsigned x){return (x*7u)^58u;}
extern "C" __attribute__((noinline)) unsigned f59(unsigned x){return (x*7u)^59u;}
extern "C" __attribute__((noinline)) unsigned f60(unsigned x){return (x*7u)^60u;}
extern "C" __attribute__((noinline)) unsigned f61(unsigned x){return (x*7u)^61u;}
extern "C" __attribute__((noinline)) unsigned f62(unsigned x){return (x*7u)^62u;}
extern "C" __attribute__((noinline)) unsigned f63(unsigned x){return (x*7u)^63u;}
extern "C" __attribute__((noinline)) unsigned f64(unsigned x){return (x*7u)^64u;}
extern "C" __attribute__((noinline)) unsigned f65(unsigned x){return (x*7u)^65u;}
extern "C" __attribute__((noinline)) unsigned f66(unsigned x){return (x*7u)^66u;}
extern "C" __attribute__((noinline)) unsigned f67(unsigned x){return (x*7u)^67u;}
extern "C" __attribute__((noinline)) unsigned f68(unsigned x){return (x*7u)^68u;}
extern "C" __attribute__((noinline)) unsigned f69(unsigned x){return (x*7u)^69u;}
extern "C" __attribute__((noinline)) unsigned f70(unsigned x){return (x*7u)^70u;}
extern "C" __attribute__((noinline)) unsigned f71(unsigned x){return (x*7u)^71u;}
extern "C" __attribute__((noinline)) unsigned f72(unsigned x){return (x*7u)^72u;}
extern "C" __attribute__((noinline)) unsigned f73(unsigned x){return (x*7u)^73u;}
extern "C" __attribute__((noinline)) unsigned f74(unsigned x){return (x*7u)^74u;}
extern "C" __attribute__((noinline)) unsigned f75(unsigned x){return (x*7u)^75u;}
extern "C" __attribute__((noinline)) unsigned f76(unsigned x){return (x*7u)^76u;}
extern "C" __attribute__((noinline)) unsigned f77(unsigned x){return (x*7u)^77u;}
extern "C" __attribute__((noinline)) unsigned f78(unsigned x){return (x*7u)^78u;}
extern "C" __attribute__((noinline)) unsigned f79(unsigned x){return (x*7u)^79u;}
extern "C" __attribute__((noinline)) unsigned f80(unsigned x){return (x*7u)^80u;}
extern "C" __attribute__((noinline)) unsigned f81(unsigned x){return (x*7u)^81u;}
extern "C" __attribute__((noinline)) unsigned f82(unsigned x){return (x*7u)^82u;}
extern "C" __attribute__((noinline)) unsigned f83(unsigned x){return (x*7u)^83u;}
extern "C" __attribute__((noinline)) unsigned f84(unsigned x){return (x*7u)^84u;}
extern "C" __attribute__((noinline)) unsigned f85(unsigned x){return (x*7u)^85u;}
extern "C" __attribute__((noinline)) unsigned f86(unsigned x){return (x*7u)^86u;}
extern "C" __attribute__((noinline)) unsigned f87(unsigned x){return (x*7u)^87u;}
extern "C" __attribute__((noinline)) unsigned f88(unsigned x){return (x*7u)^88u;}
extern "C" __attribute__((noinline)) unsigned f89(unsigned x){return (x*7u)^89u;}
extern "C" __attribute__((noinline)) unsigned f90(unsigned x){return (x*7u)^90u;}
extern "C" __attribute__((noinline)) unsigned f91(unsigned x){return (x*7u)^91u;}
extern "C" __attribute__((noinline)) unsigned f92(unsigned x){return (x*7u)^92u;}
extern "C" __attribute__((noinline)) unsigned f93(unsigned x){return (x*7u)^93u;}
extern "C" __attribute__((noinline)) unsigned f94(unsigned x){return (x*7u)^94u;}
extern "C" __attribute__((noinline)) unsigned f95(unsigned x){return (x*7u)^95u;}
extern "C" __attribute__((noinline)) unsigned f96(unsigned x){return (x*7u)^96u;}
extern "C" __attribute__((noinline)) unsigned f97(unsigned x){return (x*7u)^97u;}
extern "C" __attribute__((noinline)) unsigned f98(unsigned x){return (x*7u)^98u;}
extern "C" __attribute__((noinline)) unsigned f99(unsigned x){return (x*7u)^99u;}
extern "C" __attribute__((noinline)) unsigned f100(unsigned x){return (x*7u)^100u;}
extern "C" __attribute__((noinline)) unsigned f101(unsigned x){return (x*7u)^101u;}
extern "C" __attribute__((noinline)) unsigned f102(unsigned x){return (x*7u)^102u;}
extern "C" __attribute__((noinline)) unsigned f103(unsigned x){return (x*7u)^103u;}
extern "C" __attribute__((noinline)) unsigned f104(unsigned x){return (x*7u)^104u;}
extern "C" __attribute__((noinline)) unsigned f105(unsigned x){return (x*7u)^105u;}
extern "C" __attribute__((noinline)) unsigned f106(unsigned x){return (x*7u)^106u;}
extern "C" __attribute__((noinline)) unsigned f107(unsigned x){return (x*7u)^107u;}
extern "C" __attribute__((noinline)) unsigned f108(unsigned x){return (x*7u)^108u;}
extern "C" __attribute__((noinline)) unsigned f109(unsigned x){return (x*7u)^109u;}
extern "C" __attribute__((noinline)) unsigned f110(unsigned x){return (x*7u)^110u;}
extern "C" __attribute__((noinline)) unsigned f111(unsigned x){return (x*7u)^111u;}
extern "C" __attribute__((noinline)) unsigned f112(unsigned x){return (x*7u)^112u;}
extern "C" __attribute__((noinline)) unsigned f113(unsigned x){return (x*7u)^113u;}
extern "C" __attribute__((noinline)) unsigned f114(unsigned x){return (x*7u)^114u;}
extern "C" __attribute__((noinline)) unsigned f115(unsigned x){return (x*7u)^115u;}
extern "C" __attribute__((noinline)) unsigned f116(unsigned x){return (x*7u)^116u;}
extern "C" __attribute__((noinline)) unsigned f117(unsigned x){return (x*7u)^117u;}
extern "C" __attribute__((noinline)) unsigned f118(unsigned x){return (x*7u)^118u;}
extern "C" __attribute__((noinline)) unsigned f119(unsigned x){return (x*7u)^119u;}
extern "C" __attribute__((noinline)) unsigned f120(unsigned x){return (x*7u)^120u;}
extern "C" __attribute__((noinline)) unsigned f121(unsigned x){return (x*7u)^121u;}
extern "C" __attribute__((noinline)) unsigned f122(unsigned x){return (x*7u)^122u;}
extern "C" __attribute__((noinline)) unsigned f123(unsigned x){return (x*7u)^123u;}
extern "C" __attribute__((noinline)) unsigned f124(unsigned x){return (x*7u)^124u;}
extern "C" __attribute__((noinline)) unsigned f125(unsigned x){return (x*7u)^125u;}
extern "C" __attribute__((noinline)) unsigned f126(unsigned x){return (x*7u)^126u;}
extern "C" __attribute__((noinline)) unsigned f127(unsigned x){return (x*7u)^127u;}
extern "C" __attribute__((noinline)) unsigned f128(unsigned x){return (x*7u)^128u;}
extern "C" __attribute__((noinline)) unsigned f129(unsigned x){return (x*7u)^129u;}
extern "C" __attribute__((noinline)) unsigned f130(unsigned x){return (x*7u)^130u;}
extern "C" __attribute__((noinline)) unsigned f131(unsigned x){return (x*7u)^131u;}
extern "C" __attribute__((noinline)) unsigned f132(unsigned x){return (x*7u)^132u;}
extern "C" __attribute__((noinline)) unsigned f133(unsigned x){return (x*7u)^133u;}
extern "C" __attribute__((noinline)) unsigned f134(unsigned x){return (x*7u)^134u;}
extern "C" __attribute__((noinline)) unsigned f135(unsigned x){return (x*7u)^135u;}
extern "C" __attribute__((noinline)) unsigned f136(unsigned x){return (x*7u)^136u;}
extern "C" __attribute__((noinline)) unsigned f137(unsigned x){return (x*7u)^137u;}
extern "C" __attribute__((noinline)) unsigned f138(unsigned x){return (x*7u)^138u;}
extern "C" __attribute__((noinline)) unsigned f139(unsigned x){return (x*7u)^139u;}
extern "C" __attribute__((noinline)) unsigned f140(unsigned x){return (x*7u)^140u;}
extern "C" __attribute__((noinline)) unsigned f141(unsigned x){return (x*7u)^141u;}
extern "C" __attribute__((noinline)) unsigned f142(unsigned x){return (x*7u)^142u;}
extern "C" __attribute__((noinline)) unsigned f143(unsigned x){return (x*7u)^143u;}
extern "C" __attribute__((noinline)) unsigned f144(unsigned x){return (x*7u)^144u;}
extern "C" __attribute__((noinline)) unsigned f145(unsigned x){return (x*7u)^145u;}
extern "C" __attribute__((noinline)) unsigned f146(unsigned x){return (x*7u)^146u;}
extern "C" __attribute__((noinline)) unsigned f147(unsigned x){return (x*7u)^147u;}
extern "C" __attribute__((noinline)) unsigned f148(unsigned x){return (x*7u)^148u;}
extern "C" __attribute__((noinline)) unsigned f149(unsigned x){return (x*7u)^149u;}
extern "C" __attribute__((noinline)) unsigned f150(unsigned x){return (x*7u)^150u;}
extern "C" __attribute__((noinline)) unsigned f151(unsigned x){return (x*7u)^151u;}
extern "C" __attribute__((noinline)) unsigned f152(unsigned x){return (x*7u)^152u;}
extern "C" __attribute__((noinline)) unsigned f153(unsigned x){return (x*7u)^153u;}
extern "C" __attribute__((noinline)) unsigned f154(unsigned x){return (x*7u)^154u;}
extern "C" __attribute__((noinline)) unsigned f155(unsigned x){return (x*7u)^155u;}
extern "C" __attribute__((noinline)) unsigned f156(unsigned x){return (x*7u)^156u;}
extern "C" __attribute__((noinline)) unsigned f157(unsigned x){return (x*7u)^157u;}
extern "C" __attribute__((noinline)) unsigned f158(unsigned x){return (x*7u)^158u;}
extern "C" __attribute__((noinline)) unsigned f159(unsigned x){return (x*7u)^159u;}
extern "C" __attribute__((noinline)) unsigned f160(unsigned x){return (x*7u)^160u;}
extern "C" __attribute__((noinline)) unsigned f161(unsigned x){return (x*7u)^161u;}
extern "C" __attribute__((noinline)) unsigned f162(unsigned x){return (x*7u)^162u;}
extern "C" __attribute__((noinline)) unsigned f163(unsigned x){return (x*7u)^163u;}
extern "C" __attribute__((noinline)) unsigned f164(unsigned x){return (x*7u)^164u;}
extern "C" __attribute__((noinline)) unsigned f165(unsigned x){return (x*7u)^165u;}
extern "C" __attribute__((noinline)) unsigned f166(unsigned x){return (x*7u)^166u;}
extern "C" __attribute__((noinline)) unsigned f167(unsigned x){return (x*7u)^167u;}
extern "C" __attribute__((noinline)) unsigned f168(unsigned x){return (x*7u)^168u;}
extern "C" __attribute__((noinline)) unsigned f169(unsigned x){return (x*7u)^169u;}
extern "C" __attribute__((noinline)) unsigned f170(unsigned x){return (x*7u)^170u;}
extern "C" __attribute__((noinline)) unsigned f171(unsigned x){return (x*7u)^171u;}
extern "C" __attribute__((noinline)) unsigned f172(unsigned x){return (x*7u)^172u;}
extern "C" __attribute__((noinline)) unsigned f173(unsigned x){return (x*7u)^173u;}
extern "C" __attribute__((noinline)) unsigned f174(unsigned x){return (x*7u)^174u;}
extern "C" __attribute__((noinline)) unsigned f175(unsigned x){return (x*7u)^175u;}
extern "C" __attribute__((noinline)) unsigned f176(unsigned x){return (x*7u)^176u;}
extern "C" __attribute__((noinline)) unsigned f177(unsigned x){return (x*7u)^177u;}
extern "C" __attribute__((noinline)) unsigned f178(unsigned x){return (x*7u)^178u;}
extern "C" __attribute__((noinline)) unsigned f179(unsigned x){return (x*7u)^179u;}
extern "C" __attribute__((noinline)) unsigned f180(unsigned x){return (x*7u)^180u;}
extern "C" __attribute__((noinline)) unsigned f181(unsigned x){return (x*7u)^181u;}
extern "C" __attribute__((noinline)) unsigned f182(unsigned x){return (x*7u)^182u;}
extern "C" __attribute__((noinline)) unsigned f183(unsigned x){return (x*7u)^183u;}
extern "C" __attribute__((noinline)) unsigned f184(unsigned x){return (x*7u)^184u;}
extern "C" __attribute__((noinline)) unsigned f185(unsigned x){return (x*7u)^185u;}
extern "C" __attribute__((noinline)) unsigned f186(unsigned x){return (x*7u)^186u;}
extern "C" __attribute__((noinline)) unsigned f187(unsigned x){return (x*7u)^187u;}
extern "C" __attribute__((noinline)) unsigned f188(unsigned x){return (x*7u)^188u;}
extern "C" __attribute__((noinline)) unsigned f189(unsigned x){return (x*7u)^189u;}
extern "C" __attribute__((noinline)) unsigned f190(unsigned x){return (x*7u)^190u;}
extern "C" __attribute__((noinline)) unsigned f191(unsigned x){return (x*7u)^191u;}
extern "C" __attribute__((noinline)) unsigned f192(unsigned x){return (x*7u)^192u;}
extern "C" __attribute__((noinline)) unsigned f193(unsigned x){return (x*7u)^193u;}
extern "C" __attribute__((noinline)) unsigned f194(unsigned x){return (x*7u)^194u;}
extern "C" __attribute__((noinline)) unsigned f195(unsigned x){return (x*7u)^195u;}
extern "C" __attribute__((noinline)) unsigned f196(unsigned x){return (x*7u)^196u;}
extern "C" __attribute__((noinline)) unsigned f197(unsigned x){return (x*7u)^197u;}
extern "C" __attribute__((noinline)) unsigned f198(unsigned x){return (x*7u)^198u;}
extern "C" __attribute__((noinline)) unsigned f199(unsigned x){return (x*7u)^199u;}
extern "C" __attribute__((noinline)) unsigned f200(unsigned x){return (x*7u)^200u;}
extern "C" __attribute__((noinline)) unsigned f201(unsigned x){return (x*7u)^201u;}
extern "C" __attribute__((noinline)) unsigned f202(unsigned x){return (x*7u)^202u;}
extern "C" __attribute__((noinline)) unsigned f203(unsigned x){return (x*7u)^203u;}
extern "C" __attribute__((noinline)) unsigned f204(unsigned x){return (x*7u)^204u;}
extern "C" __attribute__((noinline)) unsigned f205(unsigned x){return (x*7u)^205u;}
extern "C" __attribute__((noinline)) unsigned f206(unsigned x){return (x*7u)^206u;}
extern "C" __attribute__((noinline)) unsigned f207(unsigned x){return (x*7u)^207u;}
extern "C" __attribute__((noinline)) unsigned f208(unsigned x){return (x*7u)^208u;}
extern "C" __attribute__((noinline)) unsigned f209(unsigned x){return (x*7u)^209u;}
extern "C" __attribute__((noinline)) unsigned f210(unsigned x){return (x*7u)^210u;}
extern "C" __attribute__((noinline)) unsigned f211(unsigned x){return (x*7u)^211u;}
extern "C" __attribute__((noinline)) unsigned f212(unsigned x){return (x*7u)^212u;}
extern "C" __attribute__((noinline)) unsigned f213(unsigned x){return (x*7u)^213u;}
extern "C" __attribute__((noinline)) unsigned f214(unsigned x){return (x*7u)^214u;}
extern "C" __attribute__((noinline)) unsigned f215(unsigned x){return (x*7u)^215u;}
extern "C" __attribute__((noinline)) unsigned f216(unsigned x){return (x*7u)^216u;}
extern "C" __attribute__((noinline)) unsigned f217(unsigned x){return (x*7u)^217u;}
extern "C" __attribute__((noinline)) unsigned f218(unsigned x){return (x*7u)^218u;}
extern "C" __attribute__((noinline)) unsigned f219(unsigned x){return (x*7u)^219u;}
extern "C" __attribute__((noinline)) unsigned f220(unsigned x){return (x*7u)^220u;}
extern "C" __attribute__((noinline)) unsigned f221(unsigned x){return (x*7u)^221u;}
extern "C" __attribute__((noinline)) unsigned f222(unsigned x){return (x*7u)^222u;}
extern "C" __attribute__((noinline)) unsigned f223(unsigned x){return (x*7u)^223u;}
extern "C" __attribute__((noinline)) unsigned f224(unsigned x){return (x*7u)^224u;}
extern "C" __attribute__((noinline)) unsigned f225(unsigned x){return (x*7u)^225u;}
extern "C" __attribute__((noinline)) unsigned f226(unsigned x){return (x*7u)^226u;}
extern "C" __attribute__((noinline)) unsigned f227(unsigned x){return (x*7u)^227u;}
extern "C" __attribute__((noinline)) unsigned f228(unsigned x){return (x*7u)^228u;}
extern "C" __attribute__((noinline)) unsigned f229(unsigned x){return (x*7u)^229u;}
extern "C" __attribute__((noinline)) unsigned f230(unsigned x){return (x*7u)^230u;}
extern "C" __attribute__((noinline)) unsigned f231(unsigned x){return (x*7u)^231u;}
extern "C" __attribute__((noinline)) unsigned f232(unsigned x){return (x*7u)^232u;}
extern "C" __attribute__((noinline)) unsigned f233(unsigned x){return (x*7u)^233u;}
extern "C" __attribute__((noinline)) unsigned f234(unsigned x){return (x*7u)^234u;}
extern "C" __attribute__((noinline)) unsigned f235(unsigned x){return (x*7u)^235u;}
extern "C" __attribute__((noinline)) unsigned f236(unsigned x){return (x*7u)^236u;}
extern "C" __attribute__((noinline)) unsigned f237(unsigned x){return (x*7u)^237u;}
extern "C" __attribute__((noinline)) unsigned f238(unsigned x){return (x*7u)^238u;}
extern "C" __attribute__((noinline)) unsigned f239(unsigned x){return (x*7u)^239u;}
extern "C" __attribute__((noinline)) unsigned f240(unsigned x){return (x*7u)^240u;}
extern "C" __attribute__((noinline)) unsigned f241(unsigned x){return (x*7u)^241u;}
extern "C" __attribute__((noinline)) unsigned f242(unsigned x){return (x*7u)^242u;}
extern "C" __attribute__((noinline)) unsigned f243(unsigned x){return (x*7u)^243u;}
extern "C" __attribute__((noinline)) unsigned f244(unsigned x){return (x*7u)^244u;}
extern "C" __attribute__((noinline)) unsigned f245(unsigned x){return (x*7u)^245u;}
extern "C" __attribute__((noinline)) unsigned f246(unsigned x){return (x*7u)^246u;}
extern "C" __attribute__((noinline)) unsigned f247(unsigned x){return (x*7u)^247u;}
extern "C" __attribute__((noinline)) unsigned f248(unsigned x){return (x*7u)^248u;}
extern "C" __attribute__((noinline)) unsigned f249(unsigned x){return (x*7u)^249u;}
extern "C" __attribute__((noinline)) unsigned f250(unsigned x){return (x*7u)^250u;}
extern "C" __attribute__((noinline)) unsigned f251(unsigned x){return (x*7u)^251u;}
extern "C" __attribute__((noinline)) unsigned f252(unsigned x){return (x*7u)^252u;}
extern "C" __attribute__((noinline)) unsigned f253(unsigned x){return (x*7u)^253u;}
extern "C" __attribute__((noinline)) unsigned f254(unsigned x){return (x*7u)^254u;}
extern "C" __attribute__((noinline)) unsigned f255(unsigned x){return (x*7u)^255u;}
extern "C" __attribute__((noinline)) unsigned f256(unsigned x){return (x*7u)^256u;}
extern "C" __attribute__((noinline)) unsigned f257(unsigned x){return (x*7u)^257u;}
extern "C" __attribute__((noinline)) unsigned f258(unsigned x){return (x*7u)^258u;}
extern "C" __attribute__((noinline)) unsigned f259(unsigned x){return (x*7u)^259u;}
extern "C" __attribute__((noinline)) unsigned f260(unsigned x){return (x*7u)^260u;}
extern "C" __attribute__((noinline)) unsigned f261(unsigned x){return (x*7u)^261u;}
extern "C" __attribute__((noinline)) unsigned f262(unsigned x){return (x*7u)^262u;}
extern "C" __attribute__((noinline)) unsigned f263(unsigned x){return (x*7u)^263u;}
extern "C" __attribute__((noinline)) unsigned f264(unsigned x){return (x*7u)^264u;}
extern "C" __attribute__((noinline)) unsigned f265(unsigned x){return (x*7u)^265u;}
extern "C" __attribute__((noinline)) unsigned f266(unsigned x){return (x*7u)^266u;}
extern "C" __attribute__((noinline)) unsigned f267(unsigned x){return (x*7u)^267u;}
extern "C" __attribute__((noinline)) unsigned f268(unsigned x){return (x*7u)^268u;}
extern "C" __attribute__((noinline)) unsigned f269(unsigned x){return (x*7u)^269u;}
extern "C" __attribute__((noinline)) unsigned f270(unsigned x){return (x*7u)^270u;}
extern "C" __attribute__((noinline)) unsigned f271(unsigned x){return (x*7u)^271u;}
extern "C" __attribute__((noinline)) unsigned f272(unsigned x){return (x*7u)^272u;}
extern "C" __attribute__((noinline)) unsigned f273(unsigned x){return (x*7u)^273u;}
extern "C" __attribute__((noinline)) unsigned f274(unsigned x){return (x*7u)^274u;}
extern "C" __attribute__((noinline)) unsigned f275(unsigned x){return (x*7u)^275u;}
extern "C" __attribute__((noinline)) unsigned f276(unsigned x){return (x*7u)^276u;}
extern "C" __attribute__((noinline)) unsigned f277(unsigned x){return (x*7u)^277u;}
extern "C" __attribute__((noinline)) unsigned f278(unsigned x){return (x*7u)^278u;}
extern "C" __attribute__((noinline)) unsigned f279(unsigned x){return (x*7u)^279u;}
extern "C" __attribute__((noinline)) unsigned f280(unsigned x){return (x*7u)^280u;}
extern "C" __attribute__((noinline)) unsigned f281(unsigned x){return (x*7u)^281u;}
extern "C" __attribute__((noinline)) unsigned f282(unsigned x){return (x*7u)^282u;}
extern "C" __attribute__((noinline)) unsigned f283(unsigned x){return (x*7u)^283u;}
extern "C" __attribute__((noinline)) unsigned f284(unsigned x){return (x*7u)^284u;}
extern "C" __attribute__((noinline)) unsigned f285(unsigned x){return (x*7u)^285u;}
extern "C" __attribute__((noinline)) unsigned f286(unsigned x){return (x*7u)^286u;}
extern "C" __attribute__((noinline)) unsigned f287(unsigned x){return (x*7u)^287u;}
extern "C" __attribute__((noinline)) unsigned f288(unsigned x){return (x*7u)^288u;}
extern "C" __attribute__((noinline)) unsigned f289(unsigned x){return (x*7u)^289u;}
extern "C" __attribute__((noinline)) unsigned f290(unsigned x){return (x*7u)^290u;}
extern "C" __attribute__((noinline)) unsigned f291(unsigned x){return (x*7u)^291u;}
extern "C" __attribute__((noinline)) unsigned f292(unsigned x){return (x*7u)^292u;}
extern "C" __attribute__((noinline)) unsigned f293(unsigned x){return (x*7u)^293u;}
extern "C" __attribute__((noinline)) unsigned f294(unsigned x){return (x*7u)^294u;}
extern "C" __attribute__((noinline)) unsigned f295(unsigned x){return (x*7u)^295u;}
extern "C" __attribute__((noinline)) unsigned f296(unsigned x){return (x*7u)^296u;}
extern "C" __attribute__((noinline)) unsigned f297(unsigned x){return (x*7u)^297u;}
extern "C" __attribute__((noinline)) unsigned f298(unsigned x){return (x*7u)^298u;}
extern "C" __attribute__((noinline)) unsigned f299(unsigned x){return (x*7u)^299u;}
extern "C" __attribute__((noinline)) unsigned f300(unsigned x){return (x*7u)^300u;}
extern "C" __attribute__((noinline)) unsigned f301(unsigned x){return (x*7u)^301u;}
extern "C" __attribute__((noinline)) unsigned f302(unsigned x){return (x*7u)^302u;}
extern "C" __attribute__((noinline)) unsigned f303(unsigned x){return (x*7u)^303u;}
extern "C" __attribute__((noinline)) unsigned f304(unsigned x){return (x*7u)^304u;}
extern "C" __attribute__((noinline)) unsigned f305(unsigned x){return (x*7u)^305u;}
extern "C" __attribute__((noinline)) unsigned f306(unsigned x){return (x*7u)^306u;}
extern "C" __attribute__((noinline)) unsigned f307(unsigned x){return (x*7u)^307u;}
extern "C" __attribute__((noinline)) unsigned f308(unsigned x){return (x*7u)^308u;}
extern "C" __attribute__((noinline)) unsigned f309(unsigned x){return (x*7u)^309u;}
extern "C" __attribute__((noinline)) unsigned f310(unsigned x){return (x*7u)^310u;}
extern "C" __attribute__((noinline)) unsigned f311(unsigned x){return (x*7u)^311u;}
extern "C" __attribute__((noinline)) unsigned f312(unsigned x){return (x*7u)^312u;}
extern "C" __attribute__((noinline)) unsigned f313(unsigned x){return (x*7u)^313u;}
extern "C" __attribute__((noinline)) unsigned f314(unsigned x){return (x*7u)^314u;}
extern "C" __attribute__((noinline)) unsigned f315(unsigned x){return (x*7u)^315u;}
extern "C" __attribute__((noinline)) unsigned f316(unsigned x){return (x*7u)^316u;}
extern "C" __attribute__((noinline)) unsigned f317(unsigned x){return (x*7u)^317u;}
extern "C" __attribute__((noinline)) unsigned f318(unsigned x){return (x*7u)^318u;}
extern "C" __attribute__((noinline)) unsigned f319(unsigned x){return (x*7u)^319u;}
extern "C" __attribute__((noinline)) unsigned f320(unsigned x){return (x*7u)^320u;}
extern "C" __attribute__((noinline)) unsigned f321(unsigned x){return (x*7u)^321u;}
extern "C" __attribute__((noinline)) unsigned f322(unsigned x){return (x*7u)^322u;}
extern "C" __attribute__((noinline)) unsigned f323(unsigned x){return (x*7u)^323u;}
extern "C" __attribute__((noinline)) unsigned f324(unsigned x){return (x*7u)^324u;}
extern "C" __attribute__((noinline)) unsigned f325(unsigned x){return (x*7u)^325u;}
extern "C" __attribute__((noinline)) unsigned f326(unsigned x){return (x*7u)^326u;}
extern "C" __attribute__((noinline)) unsigned f327(unsigned x){return (x*7u)^327u;}
extern "C" __attribute__((noinline)) unsigned f328(unsigned x){return (x*7u)^328u;}
extern "C" __attribute__((noinline)) unsigned f329(unsigned x){return (x*7u)^329u;}
extern "C" __attribute__((noinline)) unsigned f330(unsigned x){return (x*7u)^330u;}
extern "C" __attribute__((noinline)) unsigned f331(unsigned x){return (x*7u)^331u;}
extern "C" __attribute__((noinline)) unsigned f332(unsigned x){return (x*7u)^332u;}
extern "C" __attribute__((noinline)) unsigned f333(unsigned x){return (x*7u)^333u;}
extern "C" __attribute__((noinline)) unsigned f334(unsigned x){return (x*7u)^334u;}
extern "C" __attribute__((noinline)) unsigned f335(unsigned x){return (x*7u)^335u;}
extern "C" __attribute__((noinline)) unsigned f336(unsigned x){return (x*7u)^336u;}
extern "C" __attribute__((noinline)) unsigned f337(unsigned x){return (x*7u)^337u;}
extern "C" __attribute__((noinline)) unsigned f338(unsigned x){return (x*7u)^338u;}
extern "C" __attribute__((noinline)) unsigned f339(unsigned x){return (x*7u)^339u;}
extern "C" __attribute__((noinline)) unsigned f340(unsigned x){return (x*7u)^340u;}
extern "C" __attribute__((noinline)) unsigned f341(unsigned x){return (x*7u)^341u;}
extern "C" __attribute__((noinline)) unsigned f342(unsigned x){return (x*7u)^342u;}
extern "C" __attribute__((noinline)) unsigned f343(unsigned x){return (x*7u)^343u;}
extern "C" __attribute__((noinline)) unsigned f344(unsigned x){return (x*7u)^344u;}
extern "C" __attribute__((noinline)) unsigned f345(unsigned x){return (x*7u)^345u;}
extern "C" __attribute__((noinline)) unsigned f346(unsigned x){return (x*7u)^346u;}
extern "C" __attribute__((noinline)) unsigned f347(unsigned x){return (x*7u)^347u;}
extern "C" __attribute__((noinline)) unsigned f348(unsigned x){return (x*7u)^348u;}
extern "C" __attribute__((noinline)) unsigned f349(unsigned x){return (x*7u)^349u;}
extern "C" __attribute__((noinline)) unsigned f350(unsigned x){return (x*7u)^350u;}
extern "C" __attribute__((noinline)) unsigned f351(unsigned x){return (x*7u)^351u;}
extern "C" __attribute__((noinline)) unsigned f352(unsigned x){return (x*7u)^352u;}
extern "C" __attribute__((noinline)) unsigned f353(unsigned x){return (x*7u)^353u;}
extern "C" __attribute__((noinline)) unsigned f354(unsigned x){return (x*7u)^354u;}
extern "C" __attribute__((noinline)) unsigned f355(unsigned x){return (x*7u)^355u;}
extern "C" __attribute__((noinline)) unsigned f356(unsigned x){return (x*7u)^356u;}
extern "C" __attribute__((noinline)) unsigned f357(unsigned x){return (x*7u)^357u;}
extern "C" __attribute__((noinline)) unsigned f358(unsigned x){return (x*7u)^358u;}
extern "C" __attribute__((noinline)) unsigned f359(unsigned x){return (x*7u)^359u;}
extern "C" __attribute__((noinline)) unsigned f360(unsigned x){return (x*7u)^360u;}
extern "C" __attribute__((noinline)) unsigned f361(unsigned x){return (x*7u)^361u;}
extern "C" __attribute__((noinline)) unsigned f362(unsigned x){return (x*7u)^362u;}
extern "C" __attribute__((noinline)) unsigned f363(unsigned x){return (x*7u)^363u;}
extern "C" __attribute__((noinline)) unsigned f364(unsigned x){return (x*7u)^364u;}
extern "C" __attribute__((noinline)) unsigned f365(unsigned x){return (x*7u)^365u;}
extern "C" __attribute__((noinline)) unsigned f366(unsigned x){return (x*7u)^366u;}
extern "C" __attribute__((noinline)) unsigned f367(unsigned x){return (x*7u)^367u;}
extern "C" __attribute__((noinline)) unsigned f368(unsigned x){return (x*7u)^368u;}
extern "C" __attribute__((noinline)) unsigned f369(unsigned x){return (x*7u)^369u;}
extern "C" __attribute__((noinline)) unsigned f370(unsigned x){return (x*7u)^370u;}
extern "C" __attribute__((noinline)) unsigned f371(unsigned x){return (x*7u)^371u;}
extern "C" __attribute__((noinline)) unsigned f372(unsigned x){return (x*7u)^372u;}
extern "C" __attribute__((noinline)) unsigned f373(unsigned x){return (x*7u)^373u;}
extern "C" __attribute__((noinline)) unsigned f374(unsigned x){return (x*7u)^374u;}
extern "C" __attribute__((noinline)) unsigned f375(unsigned x){return (x*7u)^375u;}
extern "C" __attribute__((noinline)) unsigned f376(unsigned x){return (x*7u)^376u;}
extern "C" __attribute__((noinline)) unsigned f377(unsigned x){return (x*7u)^377u;}
extern "C" __attribute__((noinline)) unsigned f378(unsigned x){return (x*7u)^378u;}
extern "C" __attribute__((noinline)) unsigned f379(unsigned x){return (x*7u)^379u;}
extern "C" __attribute__((noinline)) unsigned f380(unsigned x){return (x*7u)^380u;}
extern "C" __attribute__((noinline)) unsigned f381(unsigned x){return (x*7u)^381u;}
extern "C" __attribute__((noinline)) unsigned f382(unsigned x){return (x*7u)^382u;}
extern "C" __attribute__((noinline)) unsigned f383(unsigned x){return (x*7u)^383u;}
extern "C" __attribute__((noinline)) unsigned f384(unsigned x){return (x*7u)^384u;}
extern "C" __attribute__((noinline)) unsigned f385(unsigned x){return (x*7u)^385u;}
extern "C" __attribute__((noinline)) unsigned f386(unsigned x){return (x*7u)^386u;}
extern "C" __attribute__((noinline)) unsigned f387(unsigned x){return (x*7u)^387u;}
extern "C" __attribute__((noinline)) unsigned f388(unsigned x){return (x*7u)^388u;}
extern "C" __attribute__((noinline)) unsigned f389(unsigned x){return (x*7u)^389u;}
extern "C" __attribute__((noinline)) unsigned f390(unsigned x){return (x*7u)^390u;}
extern "C" __attribute__((noinline)) unsigned f391(unsigned x){return (x*7u)^391u;}
extern "C" __attribute__((noinline)) unsigned f392(unsigned x){return (x*7u)^392u;}
extern "C" __attribute__((noinline)) unsigned f393(unsigned x){return (x*7u)^393u;}
extern "C" __attribute__((noinline)) unsigned f394(unsigned x){return (x*7u)^394u;}
extern "C" __attribute__((noinline)) unsigned f395(unsigned x){return (x*7u)^395u;}
extern "C" __attribute__((noinline)) unsigned f396(unsigned x){return (x*7u)^396u;}
extern "C" __attribute__((noinline)) unsigned f397(unsigned x){return (x*7u)^397u;}
extern "C" __attribute__((noinline)) unsigned f398(unsigned x){return (x*7u)^398u;}
extern "C" __attribute__((noinline)) unsigned f399(unsigned x){return (x*7u)^399u;}
extern "C" __attribute__((noinline)) unsigned f400(unsigned x){return (x*7u)^400u;}
extern "C" __attribute__((noinline)) unsigned f401(unsigned x){return (x*7u)^401u;}
extern "C" __attribute__((noinline)) unsigned f402(unsigned x){return (x*7u)^402u;}
extern "C" __attribute__((noinline)) unsigned f403(unsigned x){return (x*7u)^403u;}
extern "C" __attribute__((noinline)) unsigned f404(unsigned x){return (x*7u)^404u;}
extern "C" __attribute__((noinline)) unsigned f405(unsigned x){return (x*7u)^405u;}
extern "C" __attribute__((noinline)) unsigned f406(unsigned x){return (x*7u)^406u;}
extern "C" __attribute__((noinline)) unsigned f407(unsigned x){return (x*7u)^407u;}
extern "C" __attribute__((noinline)) unsigned f408(unsigned x){return (x*7u)^408u;}
extern "C" __attribute__((noinline)) unsigned f409(unsigned x){return (x*7u)^409u;}
extern "C" __attribute__((noinline)) unsigned f410(unsigned x){return (x*7u)^410u;}
extern "C" __attribute__((noinline)) unsigned f411(unsigned x){return (x*7u)^411u;}
extern "C" __attribute__((noinline)) unsigned f412(unsigned x){return (x*7u)^412u;}
extern "C" __attribute__((noinline)) unsigned f413(unsigned x){return (x*7u)^413u;}
extern "C" __attribute__((noinline)) unsigned f414(unsigned x){return (x*7u)^414u;}
extern "C" __attribute__((noinline)) unsigned f415(unsigned x){return (x*7u)^415u;}
extern "C" __attribute__((noinline)) unsigned f416(unsigned x){return (x*7u)^416u;}
extern "C" __attribute__((noinline)) unsigned f417(unsigned x){return (x*7u)^417u;}
extern "C" __attribute__((noinline)) unsigned f418(unsigned x){return (x*7u)^418u;}
extern "C" __attribute__((noinline)) unsigned f419(unsigned x){return (x*7u)^419u;}
extern "C" __attribute__((noinline)) unsigned f420(unsigned x){return (x*7u)^420u;}
extern "C" __attribute__((noinline)) unsigned f421(unsigned x){return (x*7u)^421u;}
extern "C" __attribute__((noinline)) unsigned f422(unsigned x){return (x*7u)^422u;}
extern "C" __attribute__((noinline)) unsigned f423(unsigned x){return (x*7u)^423u;}
extern "C" __attribute__((noinline)) unsigned f424(unsigned x){return (x*7u)^424u;}
extern "C" __attribute__((noinline)) unsigned f425(unsigned x){return (x*7u)^425u;}
extern "C" __attribute__((noinline)) unsigned f426(unsigned x){return (x*7u)^426u;}
extern "C" __attribute__((noinline)) unsigned f427(unsigned x){return (x*7u)^427u;}
extern "C" __attribute__((noinline)) unsigned f428(unsigned x){return (x*7u)^428u;}
extern "C" __attribute__((noinline)) unsigned f429(unsigned x){return (x*7u)^429u;}
extern "C" __attribute__((noinline)) unsigned f430(unsigned x){return (x*7u)^430u;}
extern "C" __attribute__((noinline)) unsigned f431(unsigned x){return (x*7u)^431u;}
extern "C" __attribute__((noinline)) unsigned f432(unsigned x){return (x*7u)^432u;}
extern "C" __attribute__((noinline)) unsigned f433(unsigned x){return (x*7u)^433u;}
extern "C" __attribute__((noinline)) unsigned f434(unsigned x){return (x*7u)^434u;}
extern "C" __attribute__((noinline)) unsigned f435(unsigned x){return (x*7u)^435u;}
extern "C" __attribute__((noinline)) unsigned f436(unsigned x){return (x*7u)^436u;}
extern "C" __attribute__((noinline)) unsigned f437(unsigned x){return (x*7u)^437u;}
extern "C" __attribute__((noinline)) unsigned f438(unsigned x){return (x*7u)^438u;}
extern "C" __attribute__((noinline)) unsigned f439(unsigned x){return (x*7u)^439u;}
extern "C" __attribute__((noinline)) unsigned f440(unsigned x){return (x*7u)^440u;}
extern "C" __attribute__((noinline)) unsigned f441(unsigned x){return (x*7u)^441u;}
extern "C" __attribute__((noinline)) unsigned f442(unsigned x){return (x*7u)^442u;}
extern "C" __attribute__((noinline)) unsigned f443(unsigned x){return (x*7u)^443u;}
extern "C" __attribute__((noinline)) unsigned f444(unsigned x){return (x*7u)^444u;}
extern "C" __attribute__((noinline)) unsigned f445(unsigned x){return (x*7u)^445u;}
extern "C" __attribute__((noinline)) unsigned f446(unsigned x){return (x*7u)^446u;}
extern "C" __attribute__((noinline)) unsigned f447(unsigned x){return (x*7u)^447u;}
extern "C" __attribute__((noinline)) unsigned f448(unsigned x){return (x*7u)^448u;}
extern "C" __attribute__((noinline)) unsigned f449(unsigned x){return (x*7u)^449u;}
extern "C" __attribute__((noinline)) unsigned f450(unsigned x){return (x*7u)^450u;}
extern "C" __attribute__((noinline)) unsigned f451(unsigned x){return (x*7u)^451u;}
extern "C" __attribute__((noinline)) unsigned f452(unsigned x){return (x*7u)^452u;}
extern "C" __attribute__((noinline)) unsigned f453(unsigned x){return (x*7u)^453u;}
extern "C" __attribute__((noinline)) unsigned f454(unsigned x){return (x*7u)^454u;}
extern "C" __attribute__((noinline)) unsigned f455(unsigned x){return (x*7u)^455u;}
extern "C" __attribute__((noinline)) unsigned f456(unsigned x){return (x*7u)^456u;}
extern "C" __attribute__((noinline)) unsigned f457(unsigned x){return (x*7u)^457u;}
extern "C" __attribute__((noinline)) unsigned f458(unsigned x){return (x*7u)^458u;}
extern "C" __attribute__((noinline)) unsigned f459(unsigned x){return (x*7u)^459u;}
extern "C" __attribute__((noinline)) unsigned f460(unsigned x){return (x*7u)^460u;}
extern "C" __attribute__((noinline)) unsigned f461(unsigned x){return (x*7u)^461u;}
extern "C" __attribute__((noinline)) unsigned f462(unsigned x){return (x*7u)^462u;}
extern "C" __attribute__((noinline)) unsigned f463(unsigned x){return (x*7u)^463u;}
extern "C" __attribute__((noinline)) unsigned f464(unsigned x){return (x*7u)^464u;}
extern "C" __attribute__((noinline)) unsigned f465(unsigned x){return (x*7u)^465u;}
extern "C" __attribute__((noinline)) unsigned f466(unsigned x){return (x*7u)^466u;}
extern "C" __attribute__((noinline)) unsigned f467(unsigned x){return (x*7u)^467u;}
extern "C" __attribute__((noinline)) unsigned f468(unsigned x){return (x*7u)^468u;}
extern "C" __attribute__((noinline)) unsigned f469(unsigned x){return (x*7u)^469u;}
extern "C" __attribute__((noinline)) unsigned f470(unsigned x){return (x*7u)^470u;}
extern "C" __attribute__((noinline)) unsigned f471(unsigned x){return (x*7u)^471u;}
extern "C" __attribute__((noinline)) unsigned f472(unsigned x){return (x*7u)^472u;}
extern "C" __attribute__((noinline)) unsigned f473(unsigned x){return (x*7u)^473u;}
extern "C" __attribute__((noinline)) unsigned f474(unsigned x){return (x*7u)^474u;}
extern "C" __attribute__((noinline)) unsigned f475(unsigned x){return (x*7u)^475u;}
extern "C" __attribute__((noinline)) unsigned f476(unsigned x){return (x*7u)^476u;}
extern "C" __attribute__((noinline)) unsigned f477(unsigned x){return (x*7u)^477u;}
extern "C" __attribute__((noinline)) unsigned f478(unsigned x){return (x*7u)^478u;}
extern "C" __attribute__((noinline)) unsigned f479(unsigned x){return (x*7u)^479u;}
extern "C" __attribute__((noinline)) unsigned f480(unsigned x){return (x*7u)^480u;}
extern "C" __attribute__((noinline)) unsigned f481(unsigned x){return (x*7u)^481u;}
extern "C" __attribute__((noinline)) unsigned f482(unsigned x){return (x*7u)^482u;}
extern "C" __attribute__((noinline)) unsigned f483(unsigned x){return (x*7u)^483u;}
extern "C" __attribute__((noinline)) unsigned f484(unsigned x){return (x*7u)^484u;}
extern "C" __attribute__((noinline)) unsigned f485(unsigned x){return (x*7u)^485u;}
extern "C" __attribute__((noinline)) unsigned f486(unsigned x){return (x*7u)^486u;}
extern "C" __attribute__((noinline)) unsigned f487(unsigned x){return (x*7u)^487u;}
extern "C" __attribute__((noinline)) unsigned f488(unsigned x){return (x*7u)^488u;}
extern "C" __attribute__((noinline)) unsigned f489(unsigned x){return (x*7u)^489u;}
extern "C" __attribute__((noinline)) unsigned f490(unsigned x){return (x*7u)^490u;}
extern "C" __attribute__((noinline)) unsigned f491(unsigned x){return (x*7u)^491u;}
extern "C" __attribute__((noinline)) unsigned f492(unsigned x){return (x*7u)^492u;}
extern "C" __attribute__((noinline)) unsigned f493(unsigned x){return (x*7u)^493u;}
extern "C" __attribute__((noinline)) unsigned f494(unsigned x){return (x*7u)^494u;}
extern "C" __attribute__((noinline)) unsigned f495(unsigned x){return (x*7u)^495u;}
extern "C" __attribute__((noinline)) unsigned f496(unsigned x){return (x*7u)^496u;}
extern "C" __attribute__((noinline)) unsigned f497(unsigned x){return (x*7u)^497u;}
extern "C" __attribute__((noinline)) unsigned f498(unsigned x){return (x*7u)^498u;}
extern "C" __attribute__((noinline)) unsigned f499(unsigned x){return (x*7u)^499u;}