extern "C" __attribute__((noinline)) unsigned f0(unsigned x){return (x*7u)^0u;}
extern "C" __attribute__((noinline)) unsigned f1(unsigned x){return (x*7u)^1u;}
extern "C" __attribute__((noinline)) unsigned f2(unsigned x){return (x*7u)^2u;}
extern "C" __attribute__((noinline)) unsigned f3(unsigned x){return (x*7u)^3u;}
extern "C" __attribute__((noinline)) unsigned f4(unsigned x){return (x*7u)^4u;}
extern "C" __attribute__((noinline)) unsigned f5(unsigned x){return (x*7u)^5u;}
extern "C" __attribute__((noinline)) unsigned f6(unsigned x){return (x*7u)^6u;}
extern "C" __attribute__((noinline)) unsigned f7(unsigned x){return (x*7u)^7u;}
extern "C" __attribute__((noinline)) unsigned f8(unsigned x){return (x*7u)^8u;}
extern "C" __attribute__((noinline)) unsigned f9(unsigned x){return (x*7u)^9u;}
extern "C" __attribute__((noinline)) unsigned f10(unsigned x){return (x*7u)^10u;}
extern "C" __attribute__((noinline)) unsigned f11(unsigned x){return (x*7u)^11u;}
extern "C" __attribute__((noinline)) unsigned f12(unsigned x){return (x*7u)^12u;}
extern "C" __attribute__((noinline)) unsigned f13(unsigned x){return (x*7u)^13u;}
extern "C" __attribute__((noinline)) unsigned f14(unsigned x){return (x*7u)^14u;}
extern "C" __attribute__((noinline)) unsigned f15(unsigned x){return (x*7u)^15u;}
extern "C" __attribute__((noinline)) unsigned f16(unsigned x){return (x*7u)^16u;}
extern "C" __attribute__((noinline)) unsigned f17(unsigned x){return (x*7u)^17u;}
extern "C" __attribute__((noinline)) unsigned f18(unsigned x){return (x*7u)^18u;}
extern "C" __attribute__((noinline)) unsigned f19(unsigned x){return (x*7u)^19u;}
extern "C" __attribute__((noinline)) unsigned f20(unsigned x){return (x*7u)^20u;}
extern "C" __attribute__((noinline)) unsigned f21(unsigned x){return (x*7u)^21u;}
extern "C" __attribute__((noinline)) unsigned f22(unsigned x){return (x*7u)^22u;}
extern "C" __attribute__((noinline)) unsigned f23(unsigned x){return (x*7u)^23u;}
extern "C" __attribute__((noinline)) unsigned f24(unsigned x){return (x*7u)^24u;}
extern "C" __attribute__((noinline)) unsigned f25(unsigned x){return (x*7u)^25u;}
extern "C" __attribute__((noinline)) unsigned f26(unsigned x){return (x*7u)^26u;}
extern "C" __attribute__((noinline)) unsigned f27(unsigned x){return (x*7u)^27u;}
extern "C" __attribute__((noinline)) unsigned f28(unsigned x){return (x*7u)^28u;}
extern "C" __attribute__((noinline)) unsigned f29(unsigned x){return (x*7u)^29u;}
extern "C" __attribute__((noinline)) unsigned f30(unsigned x){return (x*7u)^30u;}
extern "C" __attribute__((noinline)) unsigned f31(unsigned x){return (x*7u)^31u;}
extern "C" __attribute__((noinline)) unsigned f32(unsigned x){return (x*7u)^32u;}
extern "C" __attribute__((noinline)) unsigned f33(unsigned x){return (x*7u)^33u;}
extern "C" __attribute__((noinline)) unsigned f34(unsigned x){return (x*7u)^34u;}
extern "C" __attribute__((noinline)) unsigned f35(unsigned x){return (x*7u)^35u;}
extern "C" __attribute__((noinline)) unsigned f36(unsigned x){return (x*7u)^36u;}
extern "C" __attribute__((noinline)) unsigned f37(unsigned x){return (x*7u)^37u;}
extern "C" __attribute__((noinline)) unsigned f38(unsigned x){return (x*7u)^38u;}
extern "C" __attribute__((noinline)) unsigned f39(unsigned x){return (x*7u)^39u;}
extern "C" __attribute__((noinline)) unsigned f40(unsigned x){return (x*7u)^40u;}
extern "C" __attribute__((noinline)) unsigned f41(unsigned x){return (x*7u)^41u;}
extern "C" __attribute__((noinline)) unsigned f42(unsigned x){return (x*7u)^42u;}
extern "C" __attribute__((noinline)) unsigned f43(unsigned x){return (x*7u)^43u;}
extern "C" __attribute__((noinline)) unsigned f44(unsigned x){return (x*7u)^44u;}
extern "C" __attribute__((noinline)) unsigned f45(unsigned x){return (x*7u)^45u;}
extern "C" __attribute__((noinline)) unsigned f46(unsigned x){return (x*7u)^46u;}
extern "C" __attribute__((noinline)) unsigned f47(unsigned x){return (x*7u)^47u;}
extern "C" __attribute__((noinline)) unsigned f48(unsigned x){return (x*7u)^48u;}
extern "C" __attribute__((noinline)) unsigned f49(unsigned x){return (x*7u)^49u;}
extern "C" __attribute__((noinline)) unsigned f50(unsigned x){return (x*7u)^50u;}
extern "C" __attribute__((noinline)) unsigned f51(unsigned x){return (x*7u)^51u;}
extern "C" __attribute__((noinline)) unsigned f52(unsigned x){return (x*7u)^52u;}
extern "C" __attribute__((noinline)) unsigned f53(unsigned x){return (x*7u)^53u;}
extern "C" __attribute__((noinline)) unsigned f54(unsigned x){return (x*7u)^54u;}
extern "C" __attribute__((noinline)) unsigned f55(unsigned x){return (x*7u)^55u;}
extern "C" __attribute__((noinline)) unsigned f56(unsigned x){return (x*7u)^56u;}
extern "C" __attribute__((noinline)) unsigned f57(unsigned x){return (x*7u)^57u;}
extern "C" __attribute__((noinline)) unsigned f58(unsigned x){return (x*7u)^58u;}
extern "C" __attribute__((noinline)) unsigned f59(unsigned x){return (x*7u)^59u;}
extern "C" __attribute__((noinline)) unsigned f60(unsigned x){return (x*7u)^60u;}
extern "C" __attribute__((noinline)) unsigned f61(unsigned x){return (x*7u)^61u;}
extern "C" __attribute__((noinline)) unsigned f62(unsigned x){return (x*7u)^62u;}
extern "C" __attribute__((noinline)) unsigned f63(unsigned x){return (x*7u)^63u;}
extern "C" __attribute__((noinline)) unsigned f64(unsigned x){return (x*7u)^64u;}
extern "C" __attribute__((noinline)) unsigned f65(unsigned x){return (x*7u)^65u;}
extern "C" __attribute__((noinline)) unsigned f66(unsigned x){return (x*7u)^66u;}
extern "C" __attribute__((noinline)) unsigned f67(unsigned x){return (x*7u)^67u;}
extern "C" __attribute__((noinline)) unsigned f68(unsigned x){return (x*7u)^68u;}
extern "C" __attribute__((noinline)) unsigned f69(unsigned x){return (x*7u)^69u;}
extern "C" __attribute__((noinline)) unsigned f70(unsigned x){return (x*7u)^70u;}
extern "C" __attribute__((noinline)) unsigned f71(unsigned x){return (x*7u)^71u;}
extern "C" __attribute__((noinline)) unsigned f72(unsigned x){return (x*7u)^72u;}
extern "C" __attribute__((noinline)) unsigned f73(unsigned x){return (x*7u)^73u;}
extern "C" __attribute__((noinline)) unsigned f74(unsigned x){return (x*7u)^74u;}
extern "C" __attribute__((noinline)) unsigned f75(unsigned x){return (x*7u)^75u;}
extern "C" __attribute__((noinline)) unsigned f76(unsigned x){return (x*7u)^76u;}
extern "C" __attribute__((noinline)) unsigned f77(unsigned x){return (x*7u)^77u;}
extern "C" __attribute__((noinline)) unsigned f78(unsigned x){return (x*7u)^78u;}
extern "C" __attribute__((noinline)) unsigned f79(unsigned x){return (x*7u)^79u;}
extern "C" __attribute__((noinline)) unsigned f80(unsigned x){return (x*7u)^80u;}
extern "C" __attribute__((noinline)) unsigned f81(unsigned x){return (x*7u)^81u;}
extern "C" __attribute__((noinline)) unsigned f82(unsigned x){return (x*7u)^82u;}
extern "C" __attribute__((noinline)) unsigned f83(unsigned x){return (x*7u)^83u;}
extern "C" __attribute__((noinline)) unsigned f84(unsigned x){return (x*7u)^84u;}
extern "C" __attribute__((noinline)) unsigned f85(unsigned x){return (x*7u)^85u;}
extern "C" __attribute__((noinline)) unsigned f86(unsigned x){return (x*7u)^86u;}
extern "C" __attribute__((noinline)) unsigned f87(unsigned x){return (x*7u)^87u;}
extern "C" __attribute__((noinline)) unsigned f88(unsigned x){return (x*7u)^88u;}
extern "C" __attribute__((noinline)) unsigned f89(unsigned x){return (x*7u)^89u;}
extern "C" __attribute__((noinline)) unsigned f90(unsigned x){return (x*7u)^90u;}
extern "C" __attribute__((noinline)) unsigned f91(unsigned x){return (x*7u)^91u;}
extern "C" __attribute__((noinline)) unsigned f92(unsigned x){return (x*7u)^92u;}
extern "C" __attribute__((noinline)) unsigned f93(unsigned x){return (x*7u)^93u;}
extern "C" __attribute__((noinline)) unsigned f94(unsigned x){return (x*7u)^94u;}
extern "C" __attribute__((noinline)) unsigned f95(unsigned x){return (x*7u)^95u;}
extern "C" __attribute__((noinline)) unsigned f96(unsigned x){return (x*7u)^96u;}
extern "C" __attribute__((noinline)) unsigned f97(unsigned x){return (x*7u)^97u;}
extern "C" __attribute__((noinline)) unsigned f98(unsigned x){return (x*7u)^98u;}
extern "C" __attribute__((noinline)) unsigned f99(unsigned x){return (x*7u)^99u;}
extern "C" __attribute__((noinline)) unsigned f100(unsigned x){return (x*7u)^100u;}
extern "C" __attribute__((noinline)) unsigned f101(unsigned x){return (x*7u)^101u;}
extern "C" __attribute__((noinline)) unsigned f102(unsigned x){return (x*7u)^102u;}
extern "C" __attribute__((noinline)) unsigned f103(unsigned x){return (x*7u)^103u;}
extern "C" __attribute__((noinline)) unsigned f104(unsigned x){return (x*7u)^104u;}
extern "C" __attribute__((noinline)) unsigned f105(unsigned x){return (x*7u)^105u;}
extern "C" __attribute__((noinline)) unsigned f106(unsigned x){return (x*7u)^106u;}
extern "C" __attribute__((noinline)) unsigned f107(unsigned x){return (x*7u)^107u;}
extern "C" __attribute__((noinline)) unsigned f108(unsigned x){return (x*7u)^108u;}
extern "C" __attribute__((noinline)) unsigned f109(unsigned x){return (x*7u)^109u;}
extern "C" __attribute__((noinline)) unsigned f110(unsigned x){return (x*7u)^110u;}
extern "C" __attribute__((noinline)) unsigned f111(unsigned x){return (x*7u)^111u;}
extern "C" __attribute__((noinline)) unsigned f112(unsigned x){return (x*7u)^112u;}
extern "C" __attribute__((noinline)) unsigned f113(unsigned x){return (x*7u)^113u;}
extern "C" __attribute__((noinline)) unsigned f114(unsigned x){return (x*7u)^114u;}
extern "C" __attribute__((noinline)) unsigned f115(unsigned x){return (x*7u)^115u;}
extern "C" __attribute__((noinline)) unsigned f116(unsigned x){return (x*7u)^116u;}
extern "C" __attribute__((noinline)) unsigned f117(unsigned x){return (x*7u)^117u;}
extern "C" __attribute__((noinline)) unsigned f118(unsigned x){return (x*7u)^118u;}
extern "C" __attribute__((noinline)) unsigned f119(unsigned x){return (x*7u)^119u;}
extern "C" __attribute__((noinline)) unsigned f120(unsigned x){return (x*7u)^120u;}
extern "C" __attribute__((noinline)) unsigned f121(unsigned x){return (x*7u)^121u;}
extern "C" __attribute__((noinline)) unsigned f122(unsigned x){return (x*7u)^122u;}
extern "C" __attribute__((noinline)) unsigned f123(unsigned x){return (x*7u)^123u;}
extern "C" __attribute__((noinline)) unsigned f124(unsigned x){return (x*7u)^124u;}
extern "C" __attribute__((noinline)) unsigned f125(unsigned x){return (x*7u)^125u;}
extern "C" __attribute__((noinline)) unsigned f126(unsigned x){return (x*7u)^126u;}
extern "C" __attribute__((noinline)) unsigned f127(unsigned x){return (x*7u)^127u;}
extern "C" __attribute__((noinline)) unsigned f128(unsigned x){return (x*7u)^128u;}
extern "C" __attribute__((noinline)) unsigned f129(unsigned x){return (x*7u)^129u;}
extern "C" __attribute__((noinline)) unsigned f130(unsigned x){return (x*7u)^130u;}
extern "C" __attribute__((noinline)) unsigned f131(unsigned x){return (x*7u)^131u;}
extern "C" __attribute__((noinline)) unsigned f132(unsigned x){return (x*7u)^132u;}
extern "C" __attribute__((noinline)) unsigned f133(unsigned x){return (x*7u)^133u;}
extern "C" __attribute__((noinline)) unsigned f134(unsigned x){return (x*7u)^134u;}
extern "C" __attribute__((noinline)) unsigned f135(unsigned x){return (x*7u)^135u;}
extern "C" __attribute__((noinline)) unsigned f136(unsigned x){return (x*7u)^136u;}
extern "C" __attribute__((noinline)) unsigned f137(unsigned x){return (x*7u)^137u;}
extern "C" __attribute__((noinline)) unsigned f138(unsigned x){return (x*7u)^138u;}
extern "C" __attribute__((noinline)) unsigned f139(unsigned x){return (x*7u)^139u;}
extern "C" __attribute__((noinline)) unsigned f140(unsigned x){return (x*7u)^140u;}
extern "C" __attribute__((noinline)) unsigned f141(unsigned x){return (x*7u)^141u;}
extern "C" __attribute__((noinline)) unsigned f142(unsigned x){return (x*7u)^142u;}
extern "C" __attribute__((noinline)) unsigned f143(unsigned x){return (x*7u)^143u;}
extern "C" __attribute__((noinline)) unsigned f144(unsigned x){return (x*7u)^144u;}
extern "C" __attribute__((noinline)) unsigned f145(unsigned x){return (x*7u)^145u;}
extern "C" __attribute__((noinline)) unsigned f146(unsigned x){return (x*7u)^146u;}
extern "C" __attribute__((noinline)) unsigned f147(unsigned x){return (x*7u)^147u;}
extern "C" __attribute__((noinline)) unsigned f148(unsigned x){return (x*7u)^148u;}
extern "C" __attribute__((noinline)) unsigned f149(unsigned x){return (x*7u)^149u;}
extern "C" __attribute__((noinline)) unsigned f150(unsigned x){return (x*7u)^150u;}
extern "C" __attribute__((noinline)) unsigned f151(unsigned x){return (x*7u)^151u;}
extern "C" __attribute__((noinline)) unsigned f152(unsigned x){return (x*7u)^152u;}
extern "C" __attribute__((noinline)) unsigned f153(unsigned x){return (x*7u)^153u;}
extern "C" __attribute__((noinline)) unsigned f154(unsigned x){return (x*7u)^154u;}
extern "C" __attribute__((noinline)) unsigned f155(unsigned x){return (x*7u)^155u;}
extern "C" __attribute__((noinline)) unsigned f156(unsigned x){return (x*7u)^156u;}
extern "C" __attribute__((noinline)) unsigned f157(unsigned x){return (x*7u)^157u;}
extern "C" __attribute__((noinline)) unsigned f158(unsigned x){return (x*7u)^158u;}
extern "C" __attribute__((noinline)) unsigned f159(unsigned x){return (x*7u)^159u;}
extern "C" __attribute__((noinline)) unsigned f160(unsigned x){return (x*7u)^160u;}
extern "C" __attribute__((noinline)) unsigned f161(unsigned x){return (x*7u)^161u;}
extern "C" __attribute__((noinline)) unsigned f162(unsigned x){return (x*7u)^162u;}
extern "C" __attribute__((noinline)) unsigned f163(unsigned x){return (x*7u)^163u;}
extern "C" __attribute__((noinline)) unsigned f164(unsigned x){return (x*7u)^164u;}
extern "C" __attribute__((noinline)) unsigned f165(unsigned x){return (x*7u)^165u;}
extern "C" __attribute__((noinline)) unsigned f166(unsigned x){return (x*7u)^166u;}
extern "C" __attribute__((noinline)) unsigned f167(unsigned x){return (x*7u)^167u;}
extern "C" __attribute__((noinline)) unsigned f168(unsigned x){return (x*7u)^168u;}
extern "C" __attribute__((noinline)) unsigned f169(unsigned x){return (x*7u)^169u;}
extern "C" __attribute__((noinline)) unsigned f170(unsigned x){return (x*7u)^170u;}
extern "C" __attribute__((noinline)) unsigned f171(unsigned x){return (x*7u)^171u;}
extern "C" __attribute__((noinline)) unsigned f172(unsigned x){return (x*7u)^172u;}
extern "C" __attribute__((noinline)) unsigned f173(unsigned x){return (x*7u)^173u;}
extern "C" __attribute__((noinline)) unsigned f174(unsigned x){return (x*7u)^174u;}
extern "C" __attribute__((noinline)) unsigned f175(unsigned x){return (x*7u)^175u;}
extern "C" __attribute__((noinline)) unsigned f176(unsigned x){return (x*7u)^176u;}
extern "C" __attribute__((noinline)) unsigned f177(unsigned x){return (x*7u)^177u;}
extern "C" __attribute__((noinline)) unsigned f178(unsigned x){return (x*7u)^178u;}
extern "C" __attribute__((noinline)) unsigned f179(unsigned x){return (x*7u)^179u;}
extern "C" __attribute__((noinline)) unsigned f180(unsigned x){return (x*7u)^180u;}
extern "C" __attribute__((noinline)) unsigned f181(unsigned x){return (x*7u)^181u;}
extern "C" __attribute__((noinline)) unsigned f182(unsigned x){return (x*7u)^182u;}
extern "C" __attribute__((noinline)) unsigned f183(unsigned x){return (x*7u)^183u;}
extern "C" __attribute__((noinline)) unsigned f184(unsigned x){return (x*7u)^184u;}
extern "C" __attribute__((noinline)) unsigned f185(unsigned x){return (x*7u)^185u;}
extern "C" __attribute__((noinline)) unsigned f186(unsigned x){return (x*7u)^186u;}
extern "C" __attribute__((noinline)) unsigned f187(unsigned x){return (x*7u)^187u;}
extern "C" __attribute__((noinline)) unsigned f188(unsigned x){return (x*7u)^188u;}
extern "C" __attribute__((noinline)) unsigned f189(unsigned x){return (x*7u)^189u;}
extern "C" __attribute__((noinline)) unsigned f190(unsigned x){return (x*7u)^190u;}
extern "C" __attribute__((noinline)) unsigned f191(unsigned x){return (x*7u)^191u;}
extern "C" __attribute__((noinline)) unsigned f192(unsigned x){return (x*7u)^192u;}
extern "C" __attribute__((noinline)) unsigned f193(unsigned x){return (x*7u)^193u;}
extern "C" __attribute__((noinline)) unsigned f194(unsigned x){return (x*7u)^194u;}
extern "C" __attribute__((noinline)) unsigned f195(unsigned x){return (x*7u)^195u;}
extern "C" __attribute__((noinline)) unsigned f196(unsigned x){return (x*7u)^196u;}
extern "C" __attribute__((noinline)) unsigned f197(unsigned x){return (x*7u)^197u;}
extern "C" __attribute__((noinline)) unsigned f198(unsigned x){return (x*7u)^198u;}
extern "C" __attribute__((noinline)) unsigned f199(unsigned x){return (x*7u)^199u;}