#ifndef GEN_CALLDESCRIPTORSSCENE_H
#define GEN_CALLDESCRIPTORSSCENE_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include "LayoutScene.h"

class CAllDescriptorsScene : public CLayoutScene
{
public:
    virtual ~CAllDescriptorsScene();
    virtual void createDescriptors();
    CAllDescriptorsScene();

    // fields
};

#endif
