#ifndef GEN_CBOXCOLLIDERWRAPPER_H
#define GEN_CBOXCOLLIDERWRAPPER_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include <OgreVector3.h>
#include "ColliderWrapper.h"
#include "ResourceManager.h"

class CBoxColliderWrapper : public CColliderWrapper
{
public:
    virtual ~CBoxColliderWrapper();
    virtual void positionUpdated(const Ogre::Vector3&);
    void updateAlignedBox();
    CBoxColliderWrapper(CResourceManager*);

    // fields
};

#endif
