#ifndef GEN_CCAMERACONTROL_H
#define GEN_CCAMERACONTROL_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include <OgreCamera.h>
#include <OgreVector3.h>
#include "GameEnums.h"
#include "ResourceManager.h"
#include "RunicCore.h"
#include "Settings.h"
class CKeyManager;
class CMouseManager;

class CCameraControl : public CRunicCore
{
public:
    virtual ~CCameraControl();
    float getMaxDistanceToDolly();
    float getDefaultDistanceToDolly();
    static CCameraControl* getSingleton();
    void setAspectRatio(ECAMERAS, float, float);
    void setCinematicMode(bool);
    void updateGameCamera(float, CResourceManager*, Ogre::Vector3, ECAMERA_STATES);
    long long processInput(void*, CSettings*, CKeyManager*, CMouseManager*, float, bool);
    void clearCameraShakes();
    CCameraControl(Ogre::Camera*, Ogre::Camera*, Ogre::Camera*, Ogre::Camera*, Ogre::Camera*);

    // fields
    void* m_pUnknown10;
    void* m_pUnknown18;
    void* m_pUnknown20;
    void* m_pUnknown28;
    void* m_pUnknown30;
    float m_fUnknown38;
    float m_fUnknown3C;
    float m_fUnknown40;
    float m_fUnknown44;
    float m_fUnknown48;
    float m_fUnknown4C;
    float m_fUnknown50;
    float m_fUnknown54;
    unsigned char m_Unknown58[0x18] __attribute__((aligned(8)));
    unsigned char m_Unknown70[0x18] __attribute__((aligned(8)));
    bool m_bUnknown88;
    unsigned char m_gap89[0x3];
    float m_fUnknown8C;
    bool m_bUnknown90;
    unsigned char m_gap91[0x3];
    float m_fUnknown94;
    bool m_bUnknown98;
};

#endif
