#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <string>

// Global game constants and their resource names. The tables have internal
// linkage: every including TU constructs its own copy. The original keeps
// these eight tables together, in this order, in every TU that has them.
// Enumerator names are ours; values follow the table order.

enum EAlignment
{
    ALIGNMENT_NEUTRAL,
    ALIGNMENT_GOOD,
    ALIGNMENT_EVIL,
    ALIGNMENT_ALL,
    ALIGNMENT_BERSERK,
    ALIGNMENT_EVILBERSERK,
    ALIGNMENT_GOODBERSERK,
    ALIGNMENT_COUNT
};

enum EDAMAGE_TYPES
{
    DAMAGE_PHYSICAL,
    DAMAGE_MAGICAL,
    DAMAGE_FIRE,
    DAMAGE_ICE,
    DAMAGE_ELECTRIC,
    DAMAGE_POISON,
    DAMAGE_ALL,
    DAMAGE_TYPE_COUNT
};

static const std::string KLayoutFunctionNames[] =
{
    "GUIEXITGAME",
    "GUIEXITAPPLICATION",
    "GUINEWGAME",
    "GUICONTINUEGAME",
    "GUINEWGAMEMENU",
    "GUICONTINUEGAMEMENU",
    "GUICLOSEMENU",
    "GUIBACK",
    "GUIDECLINE",
    "GUIACCEPT",
    "GUIOK",
    "GUIPAUSE",
    "GUISCROLLUP",
    "GUISCROLLDOWN",
    "GUISELECT1",
    "GUISELECT2",
    "GUISELECT3",
    "GUISELECT4",
    "GUISELECT5",
    "GUISELECT6",
    "GUISELECT7",
    "GUISELECT8",
    "GUISELECT9",
    "GUISELECT10",
    "GUISELECT11",
    "GUISELECT12",
    "GUISELECT13",
    "GUISELECT14",
    "GUISELECT15",
    "GUISELECT16",
    "GUISELECT17",
    "GUISELECT18",
    "GUISELECT19",
    "GUISELECT20",
    "GUISELECT21",
    "GUISELECT22",
    "GUISELECT23",
    "GUISELECT24",
    "GUISELECT25",
    "GUISELECT26",
    "GUISELECT27",
    "GUISELECT28",
    "GUISELECT29",
    "GUISELECT30",
    "GUISELECT31",
    "GUISELECT32",
    "GUISELECT33",
    "GUISELECT34",
    "GUISELECT35",
    "GUISELECT36",
    "GUISELECT37",
    "GUISELECT38",
    "GUISELECT39",
    "GUISELECT40",
    "GUISELECT41",
    "GUISELECT42",
    "GUISELECT43",
    "GUISELECT44",
    "GUISELECT45",
    "GUISELECT46",
    "GUISELECT47",
    "GUISELECT48",
    "GUISELECT49",
    "GUISELECT50",
    "GUISELECTA",
    "GUISELECTB",
    "GUISELECTC",
    "GUISELECTD",
    "GUIFEEDPET",
    "GUIPETPASSIVE",
    "GUIPETAGGRESSIVE",
    "GUIPETDEFENSIVE",
    "GUITOGGLEINVENTORY",
    "GUITOGGLEQUESTS",
    "GUITOGGLESTATS",
    "GUITOGGLESKILLS",
    "GUITOGGLEPERKS",
    "GUITOGGLEJOURNAL",
    "GUITOGGLEPET",
    "GUITOGGLEAUTOMAP",
    "GUITOGGLEOPTIONS",
    "GUITOGGLEITEMNAMES",
    "GUIAUTOMAPZOOMIN",
    "GUIAUTOMAPZOOMOUT",
    "GUILEVELUP",
    "GUISTATSUP",
    "GUISKILLUP",
    "GUIPET1",
    "GUIPET2",
    "GUIPET3",
    "GUIDELETE1",
    "GUIDELETE2",
    "GUIDELETE3",
    "GUIDELETE4",
    "GUISETTINGSMENU",
    "GUIPETSELL",
    "NONE",
};

// The last of the 67 sound bank slots has no name.
static const std::wstring KSOUNDBANK_STRINGS[67] =
{
    L"STEP_SOUND",
    L"STRIKE_SOUND",
    L"PHYSICALHIT_SOUND",
    L"ICEHIT_SOUND",
    L"FIREHIT_SOUND",
    L"ELECTRICHIT_SOUND",
    L"POISONHIT_SOUND",
    L"SHIELDBLOCK",
    L"BLOCK",
    L"CRITICAL_SOUND",
    L"ATTACK_SOUND",
    L"IDLE_SOUND",
    L"DEATH_SOUND",
    L"ROAR_SOUND",
    L"FLEE_SOUND",
    L"MISS_SOUND",
    L"FALL_SOUND",
    L"LAND_SOUND",
    L"TAKE_SOUND",
    L"SPAWN_SOUND",
    L"USE_SOUND",
    L"EQUIP_SOUND",
    L"OPENMENU_SOUND",
    L"BUY_SOUND",
    L"ERROR_SOUND",
    L"LEVELUP_SOUND",
    L"EFFORT_SOUND",
    L"SPENDPOINT_SOUND",
    L"PORTALENTER_SOUND",
    L"POERTALEXIT_SOUND",
    L"SKILLASSIGN_SOUND",
    L"QUESTRECEIVED_SOUND",
    L"QUESTCOMPLETED_SOUND",
    L"LOWMANA_SOUND",
    L"MISSILEREFLECT_SOUND",
    L"BADEFFECT_SOUND",
    L"GOODEFFECT_SOUND",
    L"NPCDIALOG_SOUND",
    L"NPCGREET",
    L"NPCBYE",
    L"NPCPURCHASE",
    L"NPCSELL",
    L"VOICEPETINVENTORYFULL_SOUND",
    L"VOICEPETDEPARTED_SOUND",
    L"VOICEPETRETURNED_SOUND",
    L"VOICEPETFLED_SOUND",
    L"VOICEPETLEVELUP_SOUND",
    L"VOICEINVENTORYFULL_SOUND",
    L"VOICEINSUFFICIENTGOLD_SOUND",
    L"VOICEIMPOSSIBLE_SOUND",
    L"VOICECANTCAST_SOUND",
    L"VOICECANTCASTHERE_SOUND",
    L"VOICEHEALTHLOW_SOUND",
    L"VOICEMANALOW_SOUND",
    L"VOICETRAPSPRUNG_SOUND",
    L"VOICEREFRESHED_SOUND",
    L"VOICEPOWERFUL_SOUND",
    L"VOICEHEALTHY_SOUND",
    L"VOICEILL_SOUND",
    L"VOICEPOISONED_SOUND",
    L"VOICELEVELUP_SOUND",
    L"VOICEFAMEUP_SOUND",
    L"VOICESKILLUP_SOUND",
    L"VOICEFORTUNEGOOD_SOUND",
    L"VOICEFORTUNEBAD_SOUND",
    L"VOICESPELLLEARNED_SOUND",
};

static const std::wstring KALIGNMENT_STRINGS[] =
{
    L"NEUTRAL",
    L"GOOD",
    L"EVIL",
    L"ALL",
    L"BERSERK",
    L"EVILBERSERK",
    L"GOODBERSERK",
};

static const std::wstring KAITYPE_STRINGS[] =
{
    L"NORMAL",
    L"RANGEDDEFENDER",
    L"DEFENDER",
    L"RANGEDCASTER",
    L"CIRCLER",
    L"RESURRECTER",
    L"DUMMY",
};

static const std::wstring gDAMAGE_TYPES[] =
{
    L"Physical",
    L"Magical",
    L"Fire",
    L"Ice",
    L"Electric",
    L"Poison",
    L"All",
};

static const std::wstring gTARGET_TYPES[] =
{
    L"USER",
    L"ITEM",
};

static const std::wstring KSFXTypeName[] =
{
    L"STATIONARYTARGET",
    L"STATIONARYOWNER",
    L"STATIONARY",
    L"STATIONARYPORTAL",
    L"BEAM",
    L"FOLLOWOWNER",
    L"FOLLOWTARGET",
    L"PROJECTILELOCATION",
    L"PROJECTILECHARACTER",
    L"PROJECTILELOCATIONERRATIC",
    L"PROJECTILECHARACTERERRATIC",
};

static const std::wstring KCharacterNames[] =
{
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"Bksp", L"Tab", L"NA", L"NA", L"Ctr", L"Ret", L"NA", L"NA",
    L"Shift", L"Ctrl", L"Alt", L"Tab", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"space", L"pgup", L"pgdn", L"end", L"home", L"left arrow", L"up arrow", L"right arrow",
    L"down arrow", L")", L"*", L"+", L",", L"ins", L"del", L"/",
    L"0", L"1", L"2", L"3", L"4", L"5", L"6", L"7",
    L"8", L"9", L":", L";", L"<", L"=", L">", L"?",
    L"@", L"a", L"b", L"c", L"d", L"e", L"NA", L"g",
    L"h", L"i", L"j", L"k", L"l", L"m", L"n", L"o",
    L"p", L"NA", L"r", L"s", L"t", L"u", L"v", L"w",
    L"x", L"y", L"z", L"[", L"\\", L"]", L"^", L"_",
    L"NUM 0", L"NUM 1", L"NUM 2", L"NUM 3", L"NUM 4", L"NUM 5", L"NUM 6", L"NUM 7",
    L"NUM 8", L"NUM 9", L"*", L"+", L"NA", L"-", L"NA", L"F1",
    L"F2", L"F3", L"F4", L"F5", L"F6", L"F7", L"F8", L"F9",
    L"F10", L"F11", L"F12", L"{", L"|", L"}", L"~", L";",
    L"=", L".", L"-", L",", L"/", L"`", L"[", L"\\",
    L"]", L"'", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L";", L"=", L",", L"-", L".", L"/",
    L"`", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA", L"NA",
    L"NA", L"NA", L"NA", L"[", L"\\", L"]", L"'", L"NA",
    L"NA", L"NA",
};

#endif
