#ifndef EDITORDEFINES_H
#define EDITORDEFINES_H

#include <string>

// Editor events, flags and update masks with their names. The tables have
// internal linkage and every including TU constructs them. Enumerator names are
// ours, derived from the table strings.

enum EEDITOR_EVENTS
{
    EDITOR_EVENT_STOP,
    EDITOR_EVENT_PLAY,
    EDITOR_EVENT_RELOAD_TILES,
    EDITOR_EVENT_TOGGLE_LIGHTING,
    EDITOR_EVENT_SELECT_COLLIDABLE,
    EDITOR_EVENT_PAUSE_PARTICLES,
    EDITOR_EVENT_UNPAUSE_PARTICLES,
    EDITOR_EVENT_COLLISION_ALL,
    EDITOR_EVENT_COLLISION_MODELS,
    EDITOR_EVENT_COLLISION_PREFABS,
    EDITOR_EVENT_COLLISION_ROOMPIECES,
    EDITOR_EVENT_COLLISION_ROOMPROPS,
    EDITOR_EVENT_RELOAD_GRAPHS,
    EDITOR_EVENT_TOGGLE_PLAYER_LIGHT,
    EDITOR_EVENT_COUNT
};

static const std::wstring gEDITOR_EVENT_NAMES[] =
{
    L"STOP",
    L"PLAY",
    L"RELOAD TILES",
    L"TOGGLE LIGHTING",
    L"SELECT COLLIDABLE",
    L"PAUSE PARTICLES",
    L"UNPAUSE PARTICLES",
    L"COLLISION ALL",
    L"COLLISION MODELS",
    L"COLLISION PREFABS",
    L"COLLISION ROOMPIECES",
    L"COLLISION ROOMPROPS",
    L"RELOAD GRAPHS",
    L"TOGGLE PLAYER LIGHT",
};

enum EEDITOR_FLAGS
{
    EDITOR_FLAG_LOGIC_ENABLED,
    EDITOR_FLAG_INGAME_MODE,
    EDITOR_FLAG_SHOW_STATS,
    EDITOR_FLAG_EDIT_POSITION,
    EDITOR_FLAG_EDIT_SCALE,
    EDITOR_FLAG_EDIT_ORIENTATION,
    EDITOR_FLAG_EDIT_NONE,
    EDITOR_FLAG_SHOW_HELPERS,
    EDITOR_FLAG_SHOW_GRID,
    EDITOR_FLAG_SHOW_WORKING_PLANE,
    EDITOR_FLAG_SNAP_TO_GRID,
    EDITOR_FLAG_SUSPEND_EDITOR,
    EDITOR_FLAG_LIGHTING_VISIBLE,
    EDITOR_FLAG_RECALCULATE_LIGHTING,
    EDITOR_FLAG_SHOW_EDGES,
    EDITOR_FLAG_UPDATE_PARTICLES_CIRCLE,
    EDITOR_FLAG_SHOW_LOGIC_OUTPUT,
    EDITOR_FLAG_COUNT
};

static const std::wstring gEDITOR_FLAG_NAMES[] =
{
    L"LOGIC ENABLED",
    L"INGAME MODE",
    L"SHOW STATS",
    L"EDIT POSITION",
    L"EDIT SCALE",
    L"EDIT ORIENTATION",
    L"EDIT NONE",
    L"SHOW HELPERS",
    L"SHOW GRID",
    L"SHOW WORKING PLANE",
    L"SNAP TO GRID",
    L"SUSPEND EDITOR",
    L"LIGHTING VISIBLE",
    L"RECALCULATE LIGHTING",
    L"SHOW EDGES",
    L"UPDATE PARTICLES CIRCLE",
    L"SHOW LOGIC OUTPUT",
};

enum EEDITOR_UPDATE_MASKS
{
    EDITOR_UPDATE_OBJECT_SELECTION_CHANGED,
    EDITOR_UPDATE_OBJECT_DATA_CHANGED,
    EDITOR_UPDATE_OBJECTS_CREATED,
    EDITOR_UPDATE_REFRESH_TREE_VIEW,
    EDITOR_UPDATE_COUNT
};

static const std::wstring gEDITOR_UPDATE_MASKS[] =
{
    L"OBJECT SELECTION CHANGED",
    L"OBJECT DATA CHANGED",
    L"OBJECTS CREATED",
    L"REFRESH TREE VIEW",
};

#endif
