#ifndef GAMEUI_H
#define GAMEUI_H

// Partial: generated from symbols, RTTI and recovered layouts (tools/decomp/promote.py).
// Bases, virtual order and field offsets are the original ones; names, field types
// and return types are placeholders until the class's own TU is recovered.

#include <CEGUI.h>
#include <CEGUIEventArgs.h>
#include <CEGUIImageset.h>
#include <CEGUIWindow.h>
#include <CEGUIcolour.h>
#include <OgreCamera.h>
#include <OgreMatrix4.h>
#include <OgreRenderWindow.h>
#include <OgreSceneManager.h>
#include <OgreVector3.h>
#include <string>
#include "BaseUnit.h"
#include "Character.h"
#include "DynamicPropertyFile.h"
#include "GameClient.h"
#include "GameEnums.h"
#include "GameEnums.h"
#include "Item.h"
#include "Level.h"
#include "Player.h"
#include "Quest.h"
#include "ResourceManager.h"
#include "RunicCore.h"
#include "Settings.h"
#include "SoundBank.h"
#include "iMenuListener.h"
class CCinematicMenu;
class CCombineMenu;
class CConsole;
class CDropdownMenu;
class CEnchantMenu;
class CEquipment;
class CEquipmentTooltip;
class CInventoryMenu;
class CMenuManager;
class CMerchantMenu;
class CSkillFoldout;
class CSkillMenu;
class CSkillTooltip;
class CStashMenu;
class CSubMenu;
class CTextEvent;

class CGameUI : public CRunicCore
{
public:
    virtual ~CGameUI();
    virtual long long onClick(ELayoutFunction);
    static CGameUI* getSingleton();
    void requestSetGameState(EGameState, EMenu);
    void clearGameStateRequest();
    void statsChanged();
    unsigned char getDieMenuIsOpen();
    void hideModalDialogs();
    unsigned char tipMenuOpen();
    long long modalDialogOpen();
    unsigned char questDialogOpen();
    long long modalDialogOpenPartial();
    long long bothCoveredPartial();
    long long eitherCoveredPartial();
    long long leftCovered();
    long long rightCovered();
    void bothCovered();
    float leftScreenEdge();
    float rightScreenEdge();
    void toggleStatFill();
    void setLevel(CLevel*);
    long long getScreenPosition(const Ogre::Vector3*, const Ogre::Vector3*, Ogre::Matrix4);
    CItem* getMouseOverItem();
    void clearMenuMouseOvers();
    void flushProcessInput();
    void closeLeft();
    void closeRight();
    void refreshQuestMenu();
    unsigned char isCinematicMenuOpen();
    void closeCinematicMenu();
    int getUIIsInCinematic();
    long long equipmentTooltipVisible();
    void clickLeft();
    long long handle_MouseOut(const CEGUI::EventArgs&);
    long long handle_onClick(const CEGUI::EventArgs&);
    long long handle_SkillMouseOut(const CEGUI::EventArgs&);
    long long handle_SkillSelectMouseOut(const CEGUI::EventArgs&);
    void addMenuListener(EMENU_TYPE, iMenuListener*);
    void removeMenuListener(EMENU_TYPE, iMenuListener*);
    long long getQuestDialogNPC();
    int* getQuestDialogCameraOffset();
    long long handle_SkillMouseOver(const CEGUI::EventArgs&);
    float getWindowHeight();
    float getWindowWidth();
    bool mouseOverPanel(int, int);
    float getAspectRatio();
    long long handle_ToggleItemNames(const CEGUI::EventArgs&);
    void setInteractiveMenuVisible(bool);
    void toggleFPS();
    long long handle_MouseOver(const CEGUI::EventArgs&);
    void activateItemSlot(int, bool);
    void updateHardwareCursor();
    void setCursorState(ECursorState);
    long long handle_MouseThrough(const CEGUI::EventArgs&);
    float scaledY(float);
    float scaledX(float);
    void convertToScreenScale(CEGUI::Window*, bool);
    void notifyOfDeletion(CItem*);
    long long getConsoleIsOpen();
    long long processMenuInput(void*, float, bool);
    void captureProcessInput();
    void setRightButtonPressed();
    void flushInput();
    void mouseEvent(unsigned int, unsigned int);
    void keyEvent(unsigned int, unsigned int, long);
    void updateMenuUI(float, CGameClient*, Ogre::RenderWindow*);
    void addImageSet(CEGUI::Imageset*);
    void setIngameUIVisible(bool);
    void sizeComboList(CEGUI::Combobox*);
    void hideUI();
    void showUI();
    void closeMenus();
    void setActiveMenu(EMenu);
    void setWindowActive(bool);
    void canLoad();
    void canContinue();
    void reloadMenuCharacters();
    void setSmallText(std::wstring, float);
    void setBigText(std::wstring, float);
    long long handle_TogglePet(const CEGUI::EventArgs&);
    long long handle_ToggleStats(const CEGUI::EventArgs&);
    long long handle_ClickThrough(const CEGUI::EventArgs&);
    void closeAll();
    void forceInteractiveDialog(CPlayer*, CBaseUnit*, CQuest*);
    void togglePause();
    void unPause();
    long long handle_ToggleOptions(const CEGUI::EventArgs&);
    void toggleSettings();
    long long handle_ToggleMap(const CEGUI::EventArgs&);
    void toggleConsole();
    void togglePet();
    void toggleStats();
    void toggleQuest();
    long long handle_ToggleQuest(const CEGUI::EventArgs&);
    void toggleJournal();
    long long handle_ToggleJournal(const CEGUI::EventArgs&);
    void toggleSkill();
    long long handle_ToggleSkill(const CEGUI::EventArgs&);
    void toggleInventory();
    long long handle_ToggleInventory(const CEGUI::EventArgs&);
    void toggleOptions();
    void toggleDeath();
    void openModalDialog(std::wstring, std::wstring, bool);
    void toggleDialog();
    void toggleWaypointMenu();
    void hideTextEvents();
    void returnTextEventObject(CTextEvent*);
    void updateTextEvents(float, Ogre::Vector3&, Ogre::Matrix4&, bool);
    void setMouseOverItem(CItem*, bool);
    void queueTip(EContextTip);
    void returnDraggedItem();
    unsigned long menuItemClick(CCharacter*, CSubMenu*, int, bool);
    void performItemUse(CLevel&, CEquipment*, CCharacter*, CCharacter*, CCharacter*);
    void useItem(CLevel&, CEquipment*);
    void notifyOfDeletion(CCharacter*);
    void setCinematicOpen(std::wstring);
    long long handle_SkillSelectMouseOver(const CEGUI::EventArgs&);
    long long handle_SkillSelectClick(const CEGUI::EventArgs&);
    void mapEventHandlers(CEGUI::Window*);
    void mapToFunctions(CEGUI::Window*);
    long long getImageSetForIcon(const unsigned char*);
    long getImageFromImageSet(const unsigned char*);
    void cleanupReferences();
    void updateSlots();
    void setPlayer(CCharacter*);
    CTextEvent* getTextEventObject(const Ogre::Vector3&, const std::string&, float, float, CEGUI::colour, CEGUI::colour, bool);
    void addTextEvent(const Ogre::Vector3&, const std::string&, float, float, CEGUI::colour, CEGUI::colour);
    void setLoadingVisible(bool);
    long long handle_SkillClick(const CEGUI::EventArgs&);
    long long create();
    CGameUI(CSettings&, CGameClient&, void*, Ogre::RenderWindow*, Ogre::Camera*, Ogre::SceneManager*, Ogre::SceneManager*, Ogre::SceneManager*, CResourceManager*);
    void showEquipmentTooltip(CCharacter*, CEquipment*, CEquipmentTooltip*, CEquipmentTooltip*, CEquipmentTooltip*);
    void handleKeyPresses();
    unsigned char processIngameInput(void*, float, bool);
    long long processInput(CGameClient*, void*, float, bool);
    void updateIngameUI(float, CGameClient*, Ogre::RenderWindow*);
    void update(float, CGameClient*, Ogre::RenderWindow*);

    // fields
    void* m_pUnknown10;
    long long m_iUnknown18;
    long long m_iUnknown20;
    long long m_iUnknown28;
    long long m_iUnknown30;
    CCharacter* m_pCharacter;
    CLevel* m_pLevel;
    CRunicCore* m_pRunicCore;
    int m_iUnknown50;
    unsigned char m_gap54[0x4] __attribute__((aligned(4)));
    CRunicCore* m_pRunicCore_58;
    int m_iUnknown60;
    unsigned char m_gap64[0x4] __attribute__((aligned(4)));
    CItem* m_pMouseOverItem;
    int m_iUnknown70;
    unsigned char m_gap74[0x4] __attribute__((aligned(4)));
    CDynamicPropertyFile* m_pDynamicPropertyFile;
    CRunicCore* m_pRunicCore_80;
    int m_iUnknown88;
    unsigned char m_gap8C[0x4] __attribute__((aligned(4)));
    CRunicCore* m_pRunicCore_90;
    int m_iUnknown98;
    unsigned char m_gap9C[0x4] __attribute__((aligned(4)));
    CRunicCore* m_pRunicCore_A0;
    int m_iUnknownA8;
    unsigned char m_gapAC[0x4] __attribute__((aligned(4)));
    long long m_iUnknownB0;
    CRunicCore* m_pRunicCore_B8;
    int m_iUnknownC0;
    unsigned char m_gapC4[0x4] __attribute__((aligned(4)));
    CRunicCore* m_pRunicCore_C8;
    int m_iUnknownD0;
    unsigned char m_gapD4[0x4] __attribute__((aligned(4)));
    int m_iUnknownD8;
    unsigned char m_gapDC[0x4] __attribute__((aligned(4)));
    long long m_iUnknownE0;
    long long m_iUnknownE8;
    long long m_iUnknownF0;
    long long m_iUnknownF8;
    long long m_iUnknown100;
    long long m_iUnknown108;
    long long m_iUnknown110;
    long long m_iUnknown118;
    long long m_iUnknown120;
    long long m_iUnknown128;
    long long m_iUnknown130;
    long long m_iUnknown138;
    long long m_iUnknown140;
    long long m_iUnknown148;
    long long m_iUnknown150;
    long long m_iUnknown158;
    long long m_iUnknown160;
    long long m_iUnknown168;
    long long m_iUnknown170;
    long long m_iUnknown178;
    long long m_iUnknown180;
    unsigned char m_gap188[0x8] __attribute__((aligned(8)));
    long long m_iUnknown190;
    long long m_iUnknown198;
    unsigned char m_gap1A0[0x8] __attribute__((aligned(8)));
    long long m_iUnknown1A8;
    long long m_iUnknown1B0;
    long long m_iUnknown1B8;
    long long m_iUnknown1C0;
    long long m_iUnknown1C8;
    long long m_iUnknown1D0;
    long long m_iUnknown1D8;
    long long m_iUnknown1E0;
    long long m_iUnknown1E8;
    long long m_iUnknown1F0;
    long long m_iUnknown1F8;
    void* m_pUnknown200;
    void* m_pUnknown208;
    void* m_pUnknown210;
    void* m_pUnknown218;
    void* m_pUnknown220;
    long long m_iUnknown228;
    long long m_iUnknown230;
    void* m_pUnknown238;
    void* m_pUnknown240;
    long long m_iUnknown248;
    long long m_iUnknown250;
    long long m_iUnknown258;
    long long m_iUnknown260;
    long long m_iUnknown268;
    unsigned char m_gap270[0x40] __attribute__((aligned(8)));
    void* m_pUnknown2B0;
    unsigned char m_gap2B8[0x48] __attribute__((aligned(8)));
    long long m_Unknown300;
    unsigned char m_gap308[0x48] __attribute__((aligned(8)));
    long long m_Unknown350;
    unsigned char m_gap358[0x48] __attribute__((aligned(8)));
    long long m_iUnknown3A0;
    long long m_iUnknown3A8;
    unsigned char m_gap3B0[0x78] __attribute__((aligned(8)));
    void* m_pUnknown428;
    void* m_pUnknown430;
    long long m_iUnknown438;
    unsigned char m_Unknown440[0x18] __attribute__((aligned(8)));
    unsigned char m_Unknown458[0x18] __attribute__((aligned(8)));
    void* m_pUnknown470;
    long long m_iUnknown478;
    long long m_iUnknown480;
    void* m_pUnknown488;
    void* m_pUnknown490;
    void* m_pUnknown498;
    CEquipmentTooltip* m_pEquipmentTooltip;
    CEquipmentTooltip* m_pEquipmentTooltip_4A8;
    CEquipmentTooltip* m_pEquipmentTooltip_4B0;
    CSkillTooltip* m_pSkillTooltip;
    CSkillFoldout* m_pSkillFoldout;
    float m_fUnknown4C8;
    float m_fUnknown4CC;
    void* m_pUnknown4D0;
    CInventoryMenu* m_pInventoryMenu;
    void* m_pUnknown4E0;
    void* m_pUnknown4E8;
    CMerchantMenu* m_pMerchantMenu;
    CEnchantMenu* m_pEnchantMenu;
    CCombineMenu* m_pCombineMenu;
    CStashMenu* m_pStashMenu;
    void* m_pUnknown510;
    void* m_pUnknown518;
    void* m_pUnknown520;
    void* m_pUnknown528;
    void* m_pUnknown530;
    void* m_pUnknown538;
    CCinematicMenu* m_pCinematicMenu;
    CDropdownMenu* m_pDropdownMenu;
    void* m_pUnknown550;
    CSkillMenu* m_pSkillMenu;
    void* m_pUnknown560;
    void* m_pUnknown568;
    void* m_pUnknown570;
    void* m_pUnknown578;
    long long m_iUnknown580;
    CMenuManager* m_pMenuManager;
    long long m_Unknown590;
    unsigned char m_gap598[0xd10] __attribute__((aligned(8)));
    long long m_Unknown12A8;
    unsigned char m_gap12B0[0x20] __attribute__((aligned(8)));
    long long m_iUnknown12D0;
    long long m_iUnknown12D8;
    unsigned char m_gap12E0[0x18] __attribute__((aligned(8)));
    bool m_bUnknown12F8;
    bool m_bUnknown12F9;
    bool m_bUnknown12FA;
    bool m_bUnknown12FB;
    int m_Unknown12FC;
    void* m_pUnknown1300;
    CResourceManager* m_pResourceManager;
    long long m_iUnknown1310;
    void* m_pUnknown1318;
    long long m_Unknown1320;
    unsigned char m_gap1328[0x2f8] __attribute__((aligned(8)));
    long long m_Unknown1620;
    long long m_iUnknown1628;
    unsigned char m_gap1630[0x10] __attribute__((aligned(8)));
    bool m_bUnknown1640;
    bool m_bUnknown1641;
    bool m_bUnknown1642;
    bool m_bUnknown1643;
    unsigned char m_gap1644[0x4] __attribute__((aligned(4)));
    long long m_iUnknown1648;
    long long m_iUnknown1650;
    long long m_iUnknown1658;
    bool m_bUnknown1660;
    unsigned char m_gap1661[0x7];
    long long m_iUnknown1668;
    bool m_bUnknown1670;
    unsigned char m_gap1671[0x3];
    int m_iUnknown1674;
    int m_iUnknown1678;
    int m_iUnknown167C;
    float m_fUnknown1680;
    float m_fUnknown1684;
    float m_fUnknown1688;
    unsigned char m_gap168C[0x4] __attribute__((aligned(4)));
    CConsole* m_pConsole;
    void* m_pUnknown1698;
    void* m_pUnknown16A0;
    CSoundBank* m_pSoundBank;
    void* m_pUnknown16B0;
    void* m_pUnknown16B8;
    std::wstring m_sUnknown16C0;
    int m_iUnknown16C8;
    unsigned char m_fUnknown16CC[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown16D4[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown16DC[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown16E4[0x8] __attribute__((aligned(4)));
    long long m_iUnknown16EC;
    long long m_iUnknown16F4;
    long long m_iUnknown16FC;
    long long m_iUnknown1704;
    long long m_iUnknown170C;
    long long m_iUnknown1714;
    unsigned char m_fUnknown171C[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown1724[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown172C[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown1734[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown173C[0x8] __attribute__((aligned(4)));
    unsigned char m_fUnknown1744[0x8] __attribute__((aligned(4)));
    long long m_iUnknown174C;
    long long m_iUnknown1754;
    long long m_iUnknown175C;
    long long m_iUnknown1764;
    long long m_iUnknown176C;
    long long m_iUnknown1774;
    long long m_iUnknown177C;
    long long m_iUnknown1784;
    int m_iUnknown178C;
    int m_iUnknown1790;
    unsigned char m_gap1794[0x180] __attribute__((aligned(4)));
    int m_Unknown1914;
    int m_Unknown1918;
    unsigned char m_gap191C[0x4] __attribute__((aligned(4)));
    long long m_Unknown1920;
    unsigned char m_gap1928[0x8] __attribute__((aligned(8)));
    void* m_pUnknown1930;
    long long m_iUnknown1938;
    void* m_pUnknown1940;
    void* m_pUnknown1948;
    long long m_iUnknown1950;
    void* m_pUnknown1958;
    long long m_iUnknown1960;
    long long m_iUnknown1968;
    long long m_iUnknown1970;
    void* m_pUnknown1978;
    float m_fUnknown1980;
    float m_fUnknown1984;
    void* m_pUnknown1988;
    float m_fUnknown1990;
    float m_fUnknown1994;
    bool m_bUnknown1998;
    bool m_bUnknown1999;
    unsigned char m_gap199A[0x2];
    float m_fUnknown199C;
    float m_fUnknown19A0;
    float m_fUnknown19A4;
    float m_fUnknown19A8;
    float m_fUnknown19AC;
    float m_fUnknown19B0;
    float m_fUnknown19B4;
    float m_fUnknown19B8;
    float m_fUnknown19BC;
    float m_fUnknown19C0;
    float m_fUnknown19C4;
    float m_fUnknown19C8;
    float m_fUnknown19CC;
    float m_fUnknown19D0;
    float m_fUnknown19D4;
    float m_fUnknown19D8;
    float m_fUnknown19DC;
    unsigned char m_gap19E0[0x4] __attribute__((aligned(4)));
    float m_fUnknown19E4;
    float m_fUnknown19E8;
    unsigned char m_gap19EC[0x4] __attribute__((aligned(4)));
    void* m_pUnknown19F0;
    long long m_iUnknown19F8;
    long long m_iUnknown1A00;
};

#endif
