#ifndef GEN_CGEOMETRYROTATEWRAPPER_H
#define GEN_CGEOMETRYROTATEWRAPPER_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include "AffectorWrapper.h"
#include "ResourceManager.h"

class CGeometryRotateWrapper : public CAffectorWrapper
{
public:
    virtual ~CGeometryRotateWrapper();
    void setDynamicPropRotationSpeed(const float*, unsigned int);
    void getDynamicPropRotationSpeed(unsigned int&);
    CGeometryRotateWrapper(CResourceManager*);

    // fields
    unsigned char m_gap11A[0x6];
};

#endif
