#ifndef INPUTEVENTS_H
#define INPUTEVENTS_H

#include <string>

// Logic input events and their resource names. The table has internal linkage
// and every including TU constructs it. Enumerator names are ours, derived from
// the table strings (repeats get a numeric suffix).

enum EINPUT_EVENTS
{
    INPUT_EVENT_SHOW,
    INPUT_EVENT_HIDE,
    INPUT_EVENT_ENABLE,
    INPUT_EVENT_DISABLE,
    INPUT_EVENT_ENABLE_AND_SHOW,
    INPUT_EVENT_DISABLE_AND_HIDE,
    INPUT_EVENT_RESET,
    INPUT_EVENT_ADD,
    INPUT_EVENT_SUBTRACT,
    INPUT_EVENT_PLAY,
    INPUT_EVENT_STOP,
    INPUT_EVENT_PAUSE,
    INPUT_EVENT_RESUME,
    INPUT_EVENT_PLAY_LEVEL_MUSIC,
    INPUT_EVENT_INCREMENT,
    INPUT_EVENT_ACTIVATE,
    INPUT_EVENT_START_PARTICLE,
    INPUT_EVENT_STOP_PARTICLE,
    INPUT_EVENT_FORCE_STOP_PARTICLE,
    INPUT_EVENT_PAUSE_PARTICLE,
    INPUT_EVENT_RESUME_PARTICLE,
    INPUT_EVENT_PLAY_2,
    INPUT_EVENT_PLAY_BACKWARDS,
    INPUT_EVENT_STOP_2,
    INPUT_EVENT_STOP_TO_END,
    INPUT_EVENT_PAUSE_2,
    INPUT_EVENT_RESET_2,
    INPUT_EVENT_RESET_TO_END,
    INPUT_EVENT_FAST_FORWARD_TO_END,
    INPUT_EVENT_REWIND_TO_START,
    INPUT_EVENT_SET_STATE_ONE,
    INPUT_EVENT_SET_STATE_TWO,
    INPUT_EVENT_SPAWN_UNITS,
    INPUT_EVENT_DESTROY_SPAWNED_UNITS,
    INPUT_EVENT_HIDE_AND_DISABLE_SPAWNED_UNITS,
    INPUT_EVENT_INCREMENT_LEVEL_DELTA,
    INPUT_EVENT_DECREMENT_LEVEL_DELTA,
    INPUT_EVENT_ACTIVATE_WARPER,
    INPUT_EVENT_ACTIVATE_TELEPORT,
    INPUT_EVENT_ROLL,
    INPUT_EVENT_INPUT_1,
    INPUT_EVENT_INPUT_2,
    INPUT_EVENT_INPUT_3,
    INPUT_EVENT_INPUT_4,
    INPUT_EVENT_INPUT_5,
    INPUT_EVENT_INPUT_6,
    INPUT_EVENT_TRIGGER,
    INPUT_EVENT_TOGGLE,
    INPUT_EVENT_INTERACT,
    INPUT_EVENT_MAKE_INVULNERABLE,
    INPUT_EVENT_MAKE_VULNERABLE,
    INPUT_EVENT_START_CAMERA,
    INPUT_EVENT_CAMERA_OFF,
    INPUT_EVENT_FORCE_ACCEPT,
    INPUT_EVENT_FORCE_NOT_ACCEPTED,
    INPUT_EVENT_FORCE_COMPLETE,
    INPUT_EVENT_FORCE_NOT_COMPLETE,
    INPUT_EVENT_START_SKILL,
    INPUT_EVENT_STOP_SKILL,
    INPUT_EVENT_LEARN_SKILL,
    INPUT_EVENT_UNLEARN_SKILL,
    INPUT_EVENT_ALERT_MONSTER,
    INPUT_EVENT_ENABLE_TARGETING,
    INPUT_EVENT_DISABLE_TARGETING,
    INPUT_EVENT_ENABLE_TARGETING_AND_ALERT,
    INPUT_EVENT_HUNT,
    INPUT_EVENT_PLAY_3,
    INPUT_EVENT_PLAY_LOOPING,
    INPUT_EVENT_STOP_3,
    INPUT_EVENT_STOP_AND_IDLE,
    INPUT_EVENT_CANNOT_BE_TARGETED,
    INPUT_EVENT_CAN_BE_TARGETED,
    INPUT_EVENT_ADD_AS_PET,
    INPUT_EVENT_REMOVE_AS_PET,
    INPUT_EVENT_KILL_MONSTER,
    INPUT_EVENT_WARP_PETS_TO_PLAYER,
    INPUT_EVENT_HEAL_PLAYER,
    INPUT_EVENT_COLLIDABLE,
    INPUT_EVENT_NOT_COLLIDABLE,
    INPUT_EVENT_TAKE_MONEY,
    INPUT_EVENT_SHOW_TIP,
    INPUT_EVENT_CLEAR_HISTORY,
    INPUT_EVENT_STOP_SKILLS,
    INPUT_EVENT_KILL_PETS,
    INPUT_EVENT_STOP_4,
    INPUT_EVENT_START,
    INPUT_EVENT_PAUSE_3,
    INPUT_EVENT_INPUT1,
    INPUT_EVENT_INPUT2,
    INPUT_EVENT_INPUT3,
    INPUT_EVENT_INPUT4,
    INPUT_EVENT_INPUT5,
    INPUT_EVENT_COUNT
};

static const std::wstring gINPUT_EVENT_NAMES[] =
{
    L"Show",
    L"Hide",
    L"Enable",
    L"Disable",
    L"Enable and Show",
    L"Disable and Hide",
    L"Reset",
    L"Add",
    L"Subtract",
    L"Play",
    L"Stop",
    L"Pause",
    L"Resume",
    L"Play Level Music",
    L"Increment",
    L"Activate",
    L"Start Particle",
    L"Stop Particle",
    L"Force Stop Particle",
    L"Pause Particle",
    L"Resume Particle",
    L"Play",
    L"Play Backwards",
    L"Stop",
    L"Stop to End",
    L"Pause",
    L"Reset",
    L"Reset To End",
    L"Fast Forward To End",
    L"Rewind to Start",
    L"Set State One",
    L"Set State Two",
    L"Spawn Units",
    L"Destroy Spawned Units",
    L"Hide And Disable Spawned Units",
    L"Increment Level Delta",
    L"Decrement Level Delta",
    L"Activate Warper",
    L"Activate Teleport",
    L"Roll",
    L"Input 1",
    L"Input 2",
    L"Input 3",
    L"Input 4",
    L"Input 5",
    L"Input 6",
    L"Trigger",
    L"Toggle",
    L"Interact",
    L"Make Invulnerable",
    L"Make Vulnerable",
    L"Start Camera",
    L"Camera Off",
    L"Force Accept",
    L"Force Not Accepted",
    L"Force Complete",
    L"Force Not Complete",
    L"Start Skill",
    L"Stop Skill",
    L"Learn Skill",
    L"Unlearn Skill",
    L"Alert Monster",
    L"Enable Targeting",
    L"Disable Targeting",
    L"Enable Targeting & Alert",
    L"Hunt",
    L"Play",
    L"Play Looping",
    L"Stop",
    L"Stop and Idle",
    L"Cannot be Targeted",
    L"Can be Targeted",
    L"Add as Pet",
    L"Remove as Pet",
    L"Kill Monster",
    L"Warp Pets to Player",
    L"Heal Player",
    L"Collidable",
    L"Not Collidable",
    L"Take Money",
    L"Show Tip",
    L"Clear History",
    L"Stop Skills",
    L"Kill Pets",
    L"Stop",
    L"Start",
    L"Pause",
    L"Input1",
    L"Input2",
    L"Input3",
    L"Input4",
    L"Input5",
};

#endif
