#ifndef GEN_CLINEWRAPPER_H
#define GEN_CLINEWRAPPER_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include "AffectorWrapper.h"
#include "ResourceManager.h"

class CLineWrapper : public CAffectorWrapper
{
public:
    virtual ~CLineWrapper();
    CLineWrapper(CResourceManager*);

    // fields
    unsigned char m_gap11A[0x6];
};

#endif
