#ifndef GEN_CMENUMANAGER_H
#define GEN_CMENUMANAGER_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include <CEGUIWindow.h>
#include <OgreCamera.h>
#include <OgreRenderWindow.h>
#include <OgreSceneManager.h>
#include "DynamicPropertyFile.h"
#include "GameClient.h"
#include "GameEnums.h"
#include "ResourceManager.h"
#include "RunicCore.h"
#include "Settings.h"
class CContinueGameMenu;
class CGameUI;

class CMenuManager : public CRunicCore
{
public:
    virtual ~CMenuManager();
    long long canLoad();
    void closeMenus();
    void update(float, CGameClient*, Ogre::RenderWindow*);
    void flushProcessInput();
    long long processInput(void*, float, bool);
    void captureProcessInput();
    void mouseEvent(unsigned int, unsigned int);
    void keyEvent(unsigned int, unsigned int, long);
    void canContinue();
    void setActiveMenu(EMenu);
    void reloadMenuCharacters();
    long long create();
    void setWindowActive(bool);
    CMenuManager(CGameUI&, CSettings&, Ogre::Camera*, Ogre::SceneManager*, CEGUI::Window*, CResourceManager*);

    // fields
    void* m_pUnknown10;
    void* m_pUnknown18;
    long long m_iUnknown20;
    long long m_iUnknown28;
    long long m_iUnknown30;
    CDynamicPropertyFile* m_pDynamicPropertyFile;
    long long m_Unknown40;
    unsigned char m_gap48[0xd10] __attribute__((aligned(8)));
    long long m_UnknownD58;
    unsigned char m_gapD60[0x48] __attribute__((aligned(8)));
    long long m_UnknownDA8;
    bool m_bUnknownDB0;
    unsigned char m_gapDB1[0xf];
    long long m_iUnknownDC0;
    void* m_pUnknownDC8;
    void* m_pUnknownDD0;
    void* m_pUnknownDD8;
    void* m_pUnknownDE0;
    CContinueGameMenu* m_pContinueGameMenu;
    int m_UnknownDF0;
};

#endif
