#ifndef OUTPUTEVENTS_H
#define OUTPUTEVENTS_H

#include <string>

// Logic output events and their resource names. The table has internal linkage
// and every including TU constructs it (128 TUs in the original). Enumerator
// names are ours, derived from the table strings (repeats get a numeric suffix).

enum EOUTPUT_EVENTS
{
    OUTPUT_EVENT_TRIGGERED,
    OUTPUT_EVENT_TRIGGERED_FIRST_TIME,
    OUTPUT_EVENT_DEACTIVATED,
    OUTPUT_EVENT_DEACTIVATED_FIRST_TIME,
    OUTPUT_EVENT_ON_VISIBLE,
    OUTPUT_EVENT_ON_INVISIBLE,
    OUTPUT_EVENT_ENABLED,
    OUTPUT_EVENT_DISABLED,
    OUTPUT_EVENT_ACTIVATED,
    OUTPUT_EVENT_RESET,
    OUTPUT_EVENT_INITIALIZED,
    OUTPUT_EVENT_PLAYING,
    OUTPUT_EVENT_STOPPED,
    OUTPUT_EVENT_SOUND_ENDED,
    OUTPUT_EVENT_PAUSED,
    OUTPUT_EVENT_RESUMED,
    OUTPUT_EVENT_INCREMENTED,
    OUTPUT_EVENT_FIRST_INCREMENT,
    OUTPUT_EVENT_SECOND_INCREMENT,
    OUTPUT_EVENT_THIRD_INCREMENT,
    OUTPUT_EVENT_FOURTH_INCREMENT,
    OUTPUT_EVENT_FIFTH_INCREMENT,
    OUTPUT_EVENT_INCREMENT_GREATER_THEN_FIVE,
    OUTPUT_EVENT_MONSTERS_SPAWNED,
    OUTPUT_EVENT_MONSTER_KILLED,
    OUTPUT_EVENT_ALL_MONSTERS_DEAD,
    OUTPUT_EVENT_ALL_UNITS_SPAWNED,
    OUTPUT_EVENT_ITEM_PICKED_UP,
    OUTPUT_EVENT_ALL_ITEMS_PICKED_UP,
    OUTPUT_EVENT_ITEM_INTERACTED,
    OUTPUT_EVENT_ALL_ITEMS_INTERACTED_WITH,
    OUTPUT_EVENT_PARTICLE_STARTED,
    OUTPUT_EVENT_PARTICLE_STOPPED,
    OUTPUT_EVENT_PARTICLE_PAUSED,
    OUTPUT_EVENT_PARTICLE_RESUMED,
    OUTPUT_EVENT_STOPPED_2,
    OUTPUT_EVENT_STARTED,
    OUTPUT_EVENT_PAUSED_2,
    OUTPUT_EVENT_RESET_TO_BEGINNING,
    OUTPUT_EVENT_RESET_TO_END,
    OUTPUT_EVENT_LOOPED,
    OUTPUT_EVENT_STARTED_BACKWARDS,
    OUTPUT_EVENT_STARTED_FORWARDS,
    OUTPUT_EVENT_STOPPED_BACKWARDS,
    OUTPUT_EVENT_STOPPED_FORWARDS,
    OUTPUT_EVENT_FINISHED,
    OUTPUT_EVENT_STATE_ONE,
    OUTPUT_EVENT_STATE_TWO,
    OUTPUT_EVENT_ACTIVATION_FAILED,
    OUTPUT_EVENT_ONE,
    OUTPUT_EVENT_TWO,
    OUTPUT_EVENT_THREE,
    OUTPUT_EVENT_FOUR,
    OUTPUT_EVENT_FIVE,
    OUTPUT_EVENT_FAILED,
    OUTPUT_EVENT_SUCCESS,
    OUTPUT_EVENT_INTERACTED_WITH_UNIT,
    OUTPUT_EVENT_HP_90_PCT,
    OUTPUT_EVENT_HP_80_PCT,
    OUTPUT_EVENT_HP_70_PCT,
    OUTPUT_EVENT_HP_60_PCT,
    OUTPUT_EVENT_HP_50_PCT,
    OUTPUT_EVENT_HP_40_PCT,
    OUTPUT_EVENT_HP_30_PCT,
    OUTPUT_EVENT_HP_20_PCT,
    OUTPUT_EVENT_HP_10_PCT,
    OUTPUT_EVENT_MONSTER_ALERTED,
    OUTPUT_EVENT_PLAYER_HP_BELOW_90_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_80_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_70_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_60_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_50_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_40_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_30_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_20_PCT,
    OUTPUT_EVENT_PLAYER_HP_BELOW_10_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_90_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_80_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_70_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_60_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_50_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_40_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_30_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_20_PCT,
    OUTPUT_EVENT_PLAYER_HP_ABOVE_10_PCT,
    OUTPUT_EVENT_ACCEPTED,
    OUTPUT_EVENT_DECLINED,
    OUTPUT_EVENT_CAMERA_MOVING,
    OUTPUT_EVENT_CAMERA_STOPPED,
    OUTPUT_EVENT_CAMERA_PAUSING,
    OUTPUT_EVENT_CAMERA_CONTROL_RESTORED,
    OUTPUT_EVENT_INTERACTING,
    OUTPUT_EVENT_INTERACTED,
    OUTPUT_EVENT_INTERACTED_ACCEPTED,
    OUTPUT_EVENT_INTERACTED_DECLINED,
    OUTPUT_EVENT_INTERACTED_CLOSED,
    OUTPUT_EVENT_INVULNERABLE,
    OUTPUT_EVENT_VULNERABLE,
    OUTPUT_EVENT_QUEST_ACTIVE,
    OUTPUT_EVENT_QUEST_NOT_ACTIVE,
    OUTPUT_EVENT_QUEST_COMPLETE,
    OUTPUT_EVENT_QUEST_NOT_COMPLETE,
    OUTPUT_EVENT_QUEST_ABANDONED,
    OUTPUT_EVENT_SKILL_STARTED,
    OUTPUT_EVENT_SKILL_STOPPED,
    OUTPUT_EVENT_SKILL_LEARNED,
    OUTPUT_EVENT_SKILL_UNLEARNED,
    OUTPUT_EVENT_ITEM_DROPPED,
    OUTPUT_EVENT_ITEM_EQUIPPED,
    OUTPUT_EVENT_ITEM_UNEQUIPPED,
    OUTPUT_EVENT_END_OF_PATH_REACHED,
    OUTPUT_EVENT_CLICKED,
    OUTPUT_EVENT_ANIMATION_STOPPED,
    OUTPUT_EVENT_ANIMATION_PLAYING,
    OUTPUT_EVENT_SKIP_CUTSCENE,
    OUTPUT_EVENT_LEVEL_ACTIVATED,
    OUTPUT_EVENT_INSUFFICIENT_FUNDS,
    OUTPUT_EVENT_MONEY_TAKEN,
    OUTPUT_EVENT_STOP,
    OUTPUT_EVENT_START,
    OUTPUT_EVENT_PAUSE,
    OUTPUT_EVENT_OUTPUT_1,
    OUTPUT_EVENT_OUTPUT_2,
    OUTPUT_EVENT_OUTPUT_3,
    OUTPUT_EVENT_OUTPUT_4,
    OUTPUT_EVENT_OUTPUT_5,
    OUTPUT_EVENT_COUNT
};

static const std::wstring gOUTPUT_EVENTS_NAMES[] =
{
    L"Triggered",
    L"Triggered First Time",
    L"Deactivated",
    L"Deactivated First Time",
    L"On Visible",
    L"On Invisible",
    L"Enabled",
    L"Disabled",
    L"Activated",
    L"Reset",
    L"Initialized",
    L"Playing",
    L"Stopped",
    L"Sound Ended",
    L"Paused",
    L"Resumed",
    L"Incremented",
    L"First Increment",
    L"Second Increment",
    L"Third Increment",
    L"Fourth Increment",
    L"Fifth Increment",
    L"Increment Greater Then Five",
    L"Monsters Spawned",
    L"Monster Killed",
    L"All Monsters Dead",
    L"All Units Spawned",
    L"Item Picked Up",
    L"All Items Picked Up",
    L"Item Interacted",
    L"All Items Interacted With",
    L"Particle Started",
    L"Particle Stopped",
    L"Particle Paused",
    L"Particle Resumed",
    L"Stopped",
    L"Started",
    L"Paused",
    L"Reset to Beginning",
    L"Reset to End",
    L"Looped",
    L"Started Backwards",
    L"Started Forwards",
    L"Stopped Backwards",
    L"Stopped Forwards",
    L"Finished",
    L"State One",
    L"State Two",
    L"Activation Failed",
    L"One",
    L"Two",
    L"Three",
    L"Four",
    L"Five",
    L"FAILED",
    L"SUCCESS",
    L"Interacted with Unit",
    L"HP 90 PCT",
    L"HP 80 PCT",
    L"HP 70 PCT",
    L"HP 60 PCT",
    L"HP 50 PCT",
    L"HP 40 PCT",
    L"HP 30 PCT",
    L"HP 20 PCT",
    L"HP 10 PCT",
    L"Monster Alerted",
    L"Player HP Below 90 PCT",
    L"Player HP Below 80 PCT",
    L"Player HP Below 70 PCT",
    L"Player HP Below 60 PCT",
    L"Player HP Below 50 PCT",
    L"Player HP Below 40 PCT",
    L"Player HP Below 30 PCT",
    L"Player HP Below 20 PCT",
    L"Player HP Below 10 PCT",
    L"Player HP Above 90 PCT",
    L"Player HP Above 80 PCT",
    L"Player HP Above 70 PCT",
    L"Player HP Above 60 PCT",
    L"Player HP Above 50 PCT",
    L"Player HP Above 40 PCT",
    L"Player HP Above 30 PCT",
    L"Player HP Above 20 PCT",
    L"Player HP Above 10 PCT",
    L"Accepted",
    L"Declined",
    L"Camera Moving",
    L"Camera Stopped",
    L"Camera Pausing",
    L"Camera Control Restored",
    L"Interacting",
    L"Interacted",
    L"Interacted Accepted",
    L"Interacted Declined",
    L"Interacted Closed",
    L"Invulnerable",
    L"Vulnerable",
    L"Quest Active",
    L"Quest Not Active",
    L"Quest Complete",
    L"Quest Not Complete",
    L"Quest Abandoned",
    L"Skill Started",
    L"Skill Stopped",
    L"Skill Learned",
    L"Skill Unlearned",
    L"Item Dropped",
    L"Item Equipped",
    L"Item Unequipped",
    L"End of Path Reached",
    L"Clicked",
    L"Animation Stopped",
    L"Animation Playing",
    L"Skip Cutscene",
    L"Level Activated",
    L"Insufficient funds",
    L"Money Taken",
    L"Stop",
    L"Start",
    L"Pause",
    L"Output 1",
    L"Output 2",
    L"Output 3",
    L"Output 4",
    L"Output 5",
};

#endif
