#ifndef GEN_CQUESTREQUIREMENTS_H
#define GEN_CQUESTREQUIREMENTS_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include "DataGroup.h"
#include "RunicCore.h"
class CQuest;

class CQuestRequirements : public CRunicCore
{
public:
    virtual ~CQuestRequirements();
    CQuestRequirements(CQuest*);
    long long parseRequirementTag(CDataGroup*);
    char questRequirmentsHaveBeenMet();

    // fields
    CDataGroup* m_pDataGroup;
    CQuest* m_pQuest;
    int m_iUnknown20;
    int m_iUnknown24;
    int m_iUnknown28;
    int m_iUnknown2C;
    void* m_pUnknown30;
    unsigned char m_Unknown38[0x18] __attribute__((aligned(8)));
};

#endif
