#ifndef GEN_CSPAWNCLASS_H
#define GEN_CSPAWNCLASS_H

// Generated by tools/decomp/headers.py; a draft, not recovered source.

#include "Character.h"
#include "DataGroup.h"
#include "RunicCore.h"
#include "TArrayList.h"
class CSpawnClassData;

class CSpawnClass : public CRunicCore
{
public:
    virtual ~CSpawnClass();
    int calculateNumberOfChoices(CCharacter*, int, int, int, int);
    CSpawnClass(const wchar_t*);
    int rollSpawnClass(TArrayList<CDataGroup*>&, TArrayList<bool>*, CCharacter*, CCharacter*, int, unsigned int, int, int, int, int);
    void addSpawnClassData(CDataGroup*, CSpawnClassData*);

    // fields
    unsigned char m_Unknown10[0x18] __attribute__((aligned(8)));
    void* m_pUnknown28;
    int m_iUnknown30;
};

#endif
