#pragma once
#include "torchlight/enemy_ai.hpp"
#include <stdexcept>

// Minimal data generated by make_ai_cooldown_fixture.py; no original game files.
namespace test_fixture {
inline torchlight::LayoutManifest layout(const char16_t* placed_name = nullptr) {
    torchlight::LayoutManifest result;
    torchlight::LayoutObject spawner;
    spawner.id = 42;
    spawner.descriptor = u"Unit Spawner";
    spawner.properties = {
        {0, u"RESOURCE", torchlight::AdmValueType::string, std::u16string(u"FAST")},
        {0, u"GROUP", torchlight::AdmValueType::string, std::u16string(u"Monsters")}};
    result.objects.push_back(spawner);
    if (placed_name != nullptr) {
        torchlight::LayoutObject monster;
        monster.id = 43;
        monster.descriptor = u"Monster";
        monster.monster = placed_name;
        result.objects.push_back(monster);
    }
    return result;
}
struct World {
    torchlight::PakArchive archive;
    torchlight::AdmDocument document;
    torchlight::MasterResourceIndex resources;
    torchlight::UnitDefinitionLoader definitions;
    torchlight::SpawnClassCatalog spawn_classes;
    torchlight::UnitTypeHierarchy hierarchy;
    torchlight::UnitTypeResourceIndex types;
    torchlight::LayoutManifest manifest;
    torchlight::LogicRuntime logic;
    torchlight::RuntimeEntityWorld world;
    explicit World(const char* path, const char16_t* placed_name = nullptr)
        : archive(path), document(torchlight::parse_adm(archive.read_normalized("media/master.adm"))),
          resources(document), definitions(archive), spawn_classes(archive), hierarchy(archive),
          types(archive, hierarchy, resources, definitions), manifest(layout(placed_name)), logic(manifest, 1),
          world(manifest, resources, definitions, spawn_classes, types, 1, 1) {}
    void spawn(const char16_t* name = u"FAST") {
        const auto result = world.consume_spawn_requests(
            {{42, name, u"Monsters", 1}}, logic);
        if (result.entities_created != 1) throw std::runtime_error("synthetic spawn failed");
    }
};
} // namespace test_fixture
