#include <string>
#include <cstring>
#include <OgreUTFString.h>
#include "AutoTest.h"
TL_ORIGINAL(void,oldUtf8Ctor,(Ogre::UTFString*,const std::string&),"_ZN4Ogre9UTFStringC1ERKSs")
extern "C" void newUtf8Ctor(Ogre::UTFString*,const std::string&) __asm__("_ZN4Ogre9UTFStringC1ERKSs");
namespace {
struct Case{unsigned n,repeat,pattern,invalid;};
void side(void*raw,autotest::Capture&out,bool ours){Case c=*(Case*)raw;const char*good[]={"","ASCII","\xc2\xa9","\xe4\xb8\xad","\xf0\x9f\x98\x80","\xed\xa0\x80","\xf4\x8f\xbf\xbf","\xef\xbf\xbf"};const char*bad[]={"\xc2Q","\xe4Q\x80","\xf0\x9fQ\x80","\x80","\xff","\xc0\x80","\xe0\x80\x80","\xf0\x80\x80\x80"};std::string input;for(unsigned i=0;i<c.repeat;++i){input+=c.invalid?bad[c.n]:good[c.n];if(i%2)input.append("a\0b",3);}std::string shared=input;unsigned long long memory[(sizeof(Ogre::UTFString)+7)/8];std::memset(memory,c.pattern?0xa5:0,sizeof(memory));Ogre::UTFString*p=(Ogre::UTFString*)memory;int error=0;std::string message;typedef void(*Fn)(Ogre::UTFString*,const std::string&);try{autotest::invoke<Fn,Ogre::UTFString*,const std::string&>(out,ours?&newUtf8Ctor:&oldUtf8Ctor,p,input);}catch(const Ogre::UTFString::invalid_data&e){error=1;message=e.what();}catch(...){_exit(61);}out.add(&error,4);out.addText(message);out.addText(input);out.addText(shared);if(!error){size_t n=p->size(),capacity=p->capacity();out.add(&n,sizeof(n));out.add(&capacity,sizeof(capacity));out.add(p->data(),(n+1)*sizeof(Ogre::UTFString::code_point));Ogre::UTFString copy=*p;if(n)(*p)[0]=0x1234;out.add(p->data(),(n+1)*sizeof(Ogre::UTFString::code_point));out.add(copy.data(),(n+1)*sizeof(Ogre::UTFString::code_point));p->~UTFString();}}
void a(void*p,autotest::Capture&o){side(p,o,false);}void b(void*p,autotest::Capture&o){side(p,o,true);}
}
TL_TEST(equipment_utf8_constructor_production){autotest::Coverage cv("equipment_utf8_constructor_production",(uint64_t)(uintptr_t)&oldUtf8Ctor);for(unsigned n=0;n<8;++n)for(unsigned repeat=1;repeat<=5;++repeat)for(unsigned pattern=0;pattern<2;++pattern){Case c={n,repeat,pattern,0};autotest::Outcome x,y;autotest::runChild(a,&c,x);autotest::runChild(b,&c,y);if(cv.observe(host,x,y)){host->log("    utf8 constructor %u/%u/%u\n",n,repeat,pattern);cv.report(host);return 1;}}cv.report(host);return 0;}
TL_TEST(equipment_utf8_constructor_expected_exceptions){unsigned count=0;for(unsigned n=0;n<8;++n)for(unsigned repeat=1;repeat<=3;++repeat)for(unsigned pattern=0;pattern<2;++pattern){Case c={n,repeat,pattern,1};autotest::Outcome x,y;autotest::runChild(a,&c,x);autotest::runChild(b,&c,y);if(!x.reportValid||!y.reportValid||x.childStatus||y.childStatus||!x.capture.callStarted||!y.capture.callStarted||x.capture.callCompleted||y.capture.callCompleted||x.capture.issue||y.capture.issue||x.capture.length!=y.capture.length||std::memcmp(x.capture.data,y.capture.data,x.capture.length)){host->log("    utf8 unwind %u/%u/%u exits %d/%d\n",n,repeat,pattern,x.childStatus,y.childStatus);return 1;}++count;}host->log("    EXPECTED UTF8 CONSTRUCTOR EXCEPTIONS: %u matching unwinds\n",count);return 0;}
