// Exact ELF identities for the private test. No mocks or invocation yet.
#include "Detour.h"
TL_FUNCTION(dependency00,"_ZN9CBaseUnit3ISAEN9UNITTYPES10EUNITTYPESE")
TL_FUNCTION(dependency01,"_ZN10CInventory18getEquipmentInSlotEj")
TL_FUNCTION(dependency02,"_ZN10CCharacter13setTargetItemEP5CItem")
TL_FUNCTION(dependency03,"_ZN10CCharacter9castSkillEx")
TL_FUNCTION(dependency04,"_ZN7CGameUI16setMouseOverItemEP5CItemb")
TL_FUNCTION(dependency05,"_ZN7CGameUI14setCursorStateE12ECursorState")
TL_FUNCTION(dependency06,"_ZN7CGameUI20updateHardwareCursorEv")
extern "C" char dependency07[] __asm__("_ZN5CEGUI6System12getSingletonEv");
extern "C" char dependency08[] __asm__("_ZN5CEGUI6System15injectMouseMoveEff");
TL_FUNCTION(dependency09,"_ZN10CInventory15getRequiredPaneEP10CEquipment")
TL_FUNCTION(dependency10,"_ZN10CInventory11getItemPaneEj")
TL_FUNCTION(dependency11,"_ZN12CSharedStash12getSingletonEv")
TL_FUNCTION(dependency12,"_ZN10CEquipment14canUseOnTargetEP10CCharacterP9CBaseUnit")
TL_FUNCTION(dependency13,"_ZN10CEquipment11useOnTargetEP10CCharacterP9CBaseUnit")
TL_FUNCTION(dependency16,"_ZN10CSoundBank10playSampleEiPN4Ogre9SceneNodeEffb")
TL_FUNCTION(dependency17,"_ZN10CSoundBank17queueGlobalSampleEiff")
TL_FUNCTION(dependency18,"_ZN10CInventory17findEquipmentSlotEP10CEquipment")
TL_FUNCTION(dependency19,"_ZN10CInventory15removeEquipmentEP10CEquipment")
TL_FUNCTION(dependency20,"_ZN10CInventory15pickupEquipmentEP10CEquipmentib")
TL_FUNCTION(dependency21,"_ZN10CEquipment13playDropSoundEPN4Ogre9SceneNodeE")
TL_FUNCTION(dependency22,"_ZN10CEquipment9sellPriceEv")
TL_FUNCTION(dependency23,"_ZN10CCharacter8giveGoldEi")
TL_FUNCTION(dependency24,"_ZN7CPlayer8soldItemEP10CEquipment")
TL_FUNCTION(dependency25,"_ZN10CInventory15pickupEquipmentEP10CEquipmentb")
TL_FUNCTION(dependency26,"_ZN10CEquipment8buyPriceEv")
TL_FUNCTION(dependency27,"_ZN10CEquipment16addContainerItemEPS_")
TL_FUNCTION(dependency28,"_ZN10CEquipment22createElementalDamagesEv")
TL_FUNCTION(dependency29,"_ZN10CInventory13updateBonusesEv")
TL_FUNCTION(dependency30,"_ZN10CInventory21calculateEffectValuesEv")
TL_FUNCTION(dependency31,"_ZN10CInventory15refreshEquippedEv")
TL_FUNCTION(dependency32,"_Z16GetAsyncKeyStatej")
TL_FUNCTION(dependency33,"_ZN13CMerchantMenu6setTabEi")
TL_FUNCTION(dependency34,"_ZN10CEquipment13playTakeSoundEPN4Ogre9SceneNodeE")
extern "C" char dependency35[] __asm__("_ZN5CEGUI6Window14addChildWindowEPS0_");
TL_FUNCTION(dependency36,"_ZN7CGameUI7scaledYEf")
extern "C" char dependency37[] __asm__("_ZN5CEGUI6Window11setPositionERKNS_8UVector2E");
extern "C" char dependency38[] __asm__("_ZN5CEGUI6Window7setSizeERKNS_8UVector2E");
TL_FUNCTION(dependency39,"_ZN19CPositionableObject11getPositionEb")
TL_FUNCTION(dependency40,"_ZN6CLevel7addItemEP5CItemRKN4Ogre7Vector3Eb")
TL_FUNCTION(dependency41,"_ZN10CStashMenu9setPetTabEi")
TL_FUNCTION(dependency42,"_ZN13CMerchantMenu9setPetTabEi")
TL_FUNCTION(dependency43,"_ZN8CPetMenu6setTabEi")
TL_FUNCTION(dependency44,"_ZN14CInventoryMenu6setTabEi")
TL_FUNCTION(dependency45,"_ZN7CGameUI17returnDraggedItemEv")
TL_FUNCTION(dependency46,"_ZN10CInventory8canEquipEP10CEquipmentb")
TL_FUNCTION(dependency47,"_ZN10CInventory35equipEquipmentIntoFirstFreeLocationEP10CEquipment")
TL_FUNCTION(dependency48,"_ZN10CCharacter15setRenderBehindEb")
TL_FUNCTION(dependency49,"_ZN16CResourceManager10createUnitEP10CDataGroupibb")
TL_FUNCTION(dependency50,"_ZN7CPlayer25incrementJournalStatisticE17EJournalStatistici")
TL_FUNCTION(dependency51,"_ZN13CAchievements12getSingletonEv")
TL_FUNCTION(dependency52,"_ZN13CAchievements14getAchievementE13EACHIEVEMENTS")
TL_FUNCTION(dependency53,"_ZN12CAchievement13forceCompleteEv")
extern "C" char dependency54[] __asm__("_ZN5CEGUI6Window17removeChildWindowEPS0_");
TL_FUNCTION(dependency55,"_ZN7CGameUI9closeLeftEv")
TL_FUNCTION(dependency56,"_ZN7CGameUI10closeRightEv")
TL_FUNCTION(dependency57,"_ZN10CInventory18getComparisonItemsEP10CEquipmentPS1_S2_")
TL_FUNCTION(dependency59,"_ZN10CRunicCore17removeSafePointerEP12TSafePointerIPvEj")
TL_FUNCTION(dependency60,"_ZN10CRunicCore14addSafePointerEP12TSafePointerIPvE")
