#!/usr/bin/env python3
"""Moves what a decompiled TU needs from the generated headers into decomp/include.

    python3 tools/decomp/promote.py decomp/src/Graph.cpp

llm_loop.py compiles against build-decomp/include-gen (OTL_EXTRA_INCLUDE);
committed sources must build without it. For every generated header the TU
reaches:
- a class header CFoo.h becomes decomp/include/Foo.h (CFoo.h when Foo.h is
  another header), marked partial;
- the enums, globals and namespace functions the TU and those headers use
  from GenTypes.h, GenGlobals.h and GenNamespaces.h are added to
  decomp/include/GameEnums.h, GameGlobals.h and GameNamespaces.h.
Includes are rewritten and build-decomp/include-gen is regenerated, so the
generated headers stop declaring what decomp/include now declares. Ghidra's
helper macros (CONCAT44, SUB41...) are not promoted: a TU using them does not
compile afterwards.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import elfdb  # noqa: E402
import headers  # noqa: E402

ROOT = elfdb.ROOT
INCLUDE = ROOT / "decomp" / "include"
GEN = headers.OUT
SHARED = {"GenTypes.h": "GameEnums.h", "GenGlobals.h": "GameGlobals.h", "GenNamespaces.h": "GameNamespaces.h"}
GENERATED_NOTE = "// Generated by tools/decomp/headers.py; a draft, not recovered source."
PARTIAL_NOTE = ("// Partial: generated from symbols, RTTI and recovered layouts (tools/decomp/promote.py).\n"
                "// Bases, virtual order and field offsets are the original ones; names, field types\n"
                "// and return types are placeholders until the class's own TU is recovered.")


def includes(text):
    return re.findall(r'^\s*#\s*include\s+"([^"]+)"', text, re.M)


def rewrite_includes(text, renames):
    """Renames includes; a None target drops the include line."""
    text = re.sub(r'^\s*#\s*include\s+"([^"]+)"\n',
                  lambda m: "" if m.group(1) in renames and renames[m.group(1)] is None else m.group(0),
                  text, flags=re.M)
    return re.sub(r'^(\s*#\s*include\s+")([^"]+)(")',
                  lambda m: m.group(1) + renames.get(m.group(2), m.group(2)) + m.group(3), text, flags=re.M)


def guard(name):
    return re.sub(r"\W", "_", name).upper()


# -- shared declarations ----------------------------------------------------------
def enum_entries(text):
    """Name -> line, for the enums and integer typedefs (not Ghidra's helpers)."""
    text = text.split("// Ghidra's opaque types")[0]
    out = {}
    for line in text.splitlines():
        m = re.match(r"enum (\w+) \{.*\};$", line) or re.match(r"typedef [\w ]+ (\w+);$", line)
        if m:
            out[m.group(1)] = line
    return out


def global_entries(text):
    out = {}
    for line in text.splitlines():
        m = re.match(r"(?:static|extern) .*?\b(\w+)\s*(?:\[[^\]]*\])?;$", line)
        if m:
            out[m.group(1)] = line
    return out


def namespace_entries(text):
    """(namespace -> {function name -> declarations}, includes, forward declarations)."""
    spaces = {}
    for m in re.finditer(r"^namespace (\w+)\n\{\n(.*?)^\}", text, re.M | re.S):
        for line in m.group(2).splitlines():
            d = re.match(r"\s*.*?\b(\w+)\(.*\);$", line)
            if d:
                spaces.setdefault(m.group(1), {}).setdefault(d.group(1), set()).add(line.strip())
    incl = [l for l in text.splitlines() if l.startswith("#include")]
    forward = [l for l in text.splitlines() if re.match(r"(?:class|struct) \w+;$", l)]
    return spaces, incl, forward


def write_enums(entries):
    lines = [f"#ifndef {guard('GameEnums.h')}", f"#define {guard('GameEnums.h')}", "",
             "// Enums and typedefs named in symbols, promoted from the generated headers as recovered",
             "// code needs them. Enumerators are unknown until a TU defines them; move each into its",
             "// proper header when that is known.", ""]
    lines += [entries[k] for k in sorted(entries)]
    return "\n".join(lines + ["", "#endif"]) + "\n"


def write_globals(entries):
    lines = [f"#ifndef {guard('GameGlobals.h')}", f"#define {guard('GameGlobals.h')}", "",
             "// Game globals by symbol, promoted from the generated headers as recovered code needs",
             "// them; types from Hungarian prefixes or sizes until a TU defines them.", "",
             "#include <string>", ""]
    lines += [entries[k] for k in sorted(entries)]
    return "\n".join(lines + ["", "#endif"]) + "\n"


def write_namespaces(spaces, incl, forward):
    lines = [f"#ifndef {guard('GameNamespaces.h')}", f"#define {guard('GameNamespaces.h')}", "",
             "// Free functions of game namespaces by symbol, promoted from the generated headers as",
             "// recovered code needs them; return types from Ghidra until a TU defines them.", ""]
    lines += sorted(set(incl)) + sorted(set(forward)) + [""]
    for ns in sorted(spaces):
        lines += [f"namespace {ns}", "{"]
        lines += [f"    {d}" for name in sorted(spaces[ns]) for d in sorted(spaces[ns][name])]
        lines += ["}", ""]
    return "\n".join(lines + ["#endif"]) + "\n"


# -- promotion -------------------------------------------------------------------
def plan(source):
    """(class header renames, promoted texts, reached decomp/include headers)."""
    renames, texts, reached = {}, {}, {}
    queue, seen = list(includes(source.read_text())), set()
    while queue:
        name = queue.pop()
        if name in seen or name in SHARED:
            continue
        seen.add(name)
        if (INCLUDE / name).exists():
            reached[name] = (INCLUDE / name).read_text()
            queue += includes(reached[name])
            continue
        if not (GEN / name).exists():
            continue
        stem = name[:-2]
        target = (stem[1:] if re.match(r"C[A-Z]", stem) else stem) + ".h"
        if (INCLUDE / target).exists():
            target = name
        renames[name] = target
        body = (GEN / name).read_text()
        texts[target] = body
        queue += includes(body)
    return renames, texts, reached


def promote(source, regenerate=True):
    """Promotes what `source` needs; returns the decomp/include headers written."""
    renames, texts, reached = plan(source)
    used_gen = {n for t in [source.read_text(), *texts.values(), *reached.values()] for n in includes(t)} & set(SHARED)
    if not renames and not used_gen:
        return []
    renames.update(SHARED)
    alltext = "\n".join([source.read_text(), *texts.values(), *reached.values()])
    idents = set(re.findall(r"\b[A-Za-z_]\w*\b", alltext))
    written = []

    def save(name, text):
        if not (INCLUDE / name).exists() or (INCLUDE / name).read_text() != text:
            (INCLUDE / name).write_text(text)
            written.append(name)

    def shared(gen, target, merged, changed, text):
        """Writes a shared header when it gains entries; an include of the generated one
        is dropped when nothing in it is needed and the shared header does not exist yet."""
        if not merged and not (INCLUDE / target).exists():
            renames[gen] = None
        elif changed or gen in used_gen:
            save(target, text())

    old = (INCLUDE / "GameEnums.h").read_text() if (INCLUDE / "GameEnums.h").exists() else ""
    enums = enum_entries(old)
    enums.update({k: v for k, v in enum_entries((GEN / "GenTypes.h").read_text()).items() if k in idents})
    shared("GenTypes.h", "GameEnums.h", enums, enums != enum_entries(old), lambda: write_enums(enums))

    old = (INCLUDE / "GameGlobals.h").read_text() if (INCLUDE / "GameGlobals.h").exists() else ""
    globs = global_entries(old)
    globs.update({k: v for k, v in global_entries((GEN / "GenGlobals.h").read_text()).items() if k in idents})
    shared("GenGlobals.h", "GameGlobals.h", globs, globs != global_entries(old), lambda: write_globals(globs))

    old = (INCLUDE / "GameNamespaces.h").read_text() if (INCLUDE / "GameNamespaces.h").exists() else ""
    spaces, incl, forward = namespace_entries(old)
    gen_spaces, gen_incl, gen_forward = namespace_entries((GEN / "GenNamespaces.h").read_text())
    added = False
    for ns, funcs in gen_spaces.items():
        if ns not in idents:
            continue
        for name, decls in funcs.items():
            if name in idents and not decls <= spaces.get(ns, {}).get(name, set()):
                spaces.setdefault(ns, {}).setdefault(name, set()).update(decls)
                added = True
    shared("GenNamespaces.h", "GameNamespaces.h", spaces, added,
           lambda: write_namespaces(spaces, incl + (gen_incl if added else []), forward + (gen_forward if added else [])))

    for target, body in texts.items():
        body = body.replace(GENERATED_NOTE, PARTIAL_NOTE)
        body = re.sub(r"\bGEN_\w+_H\b", guard(target), body)
        save(target, rewrite_includes(body, renames))
    for name, body in reached.items():
        new = rewrite_includes(body, renames)
        if new != body:
            save(name, new)
    text = source.read_text()
    if rewrite_includes(text, renames) != text:
        source.write_text(rewrite_includes(text, renames))
    if regenerate and written:
        headers.Gen().write()
    return written


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("sources", nargs="+", type=Path)
    args = parser.parse_args()
    for source in args.sources:
        written = promote(source.resolve(), regenerate=False)
        print(f"{source}: {', '.join(written) or 'nothing to promote'}")
    headers.Gen().write()


if __name__ == "__main__":
    main()
