// GENERATED by tools/gen_menu_profiles.py -- DO NOT EDIT.
// Source: research/batch-menu-pass.json + batch *.wiring.json
// (machine code of the pinned ELF). Review against the ASM
// slices before use; see research/inventory-open.md.
#pragma once

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace torchlight {

struct MenuGrab {
    const char* key;
    const char* menu_field; // original CInventoryMenu-style field id, or "live"
};

struct MenuHandler {
    std::uint32_t id; // original handler code address
    const char* name;
};

struct MenuCreateProfile {
    const char* menu_class;
    const char* address;
    unsigned table_loop_bound;
    unsigned slot_loop_bound;
    const char* table_array_base;
    const char* slot_array_base;
    const char* index_offset;
    std::vector<MenuGrab> grabs;
    std::vector<MenuHandler> handlers;
};

inline std::vector<MenuCreateProfile> menu_create_profiles() {
    std::vector<MenuCreateProfile> out;
    out.push_back(MenuCreateProfile{
        "CInventoryMenu", "0xb569e0",
        12, 64,
        "0x80", "0x80", "0x12",
        {
            {"Blocker", "live"},
            {"BottomFrame", "0x48(%menu)"},
            {"TopFrame", "0x28(%menu)"},
            {"SlotGlow", "0x1d00(%menu)"},
            {"Close", "live"},
            {"PaperdollEquip", "live"},
            {"RotateLeft", "live"},
            {"RotateRight", "live"},
            {"dynamic:runtime table 0x14c6b20[counter]", "live"},
            {"TabBackpack", "0x9120(%menu)"},
            {"TabSpell", "0x9128(%menu)"},
            {"TabFish", "0x9130(%menu)"},
            {"SlotsEquipment", "0x9108(%menu)"},
            {"SlotsSpells", "0x9110(%menu)"},
            {"SlotsFish", "0x9118(%menu)"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
            {"Money", "0x9190(%menu)"},
            {"WeaponSwitch", "0x9198(%menu)"},
        },
        {
            {0xb458a0, "MouseThrough"},
            {0xb4d920, "CloseButton"},
            {0xb45810, "ItemClick"},
            {0xb45860, "RotateLeft"},
            {0xb45870, "EndRotateLeft"},
            {0xb45880, "RotateRight"},
            {0xb45890, "EndRotateRight"},
            {0xb4d590, "MouseOver"},
            {0xb45d30, "MouseOut"},
            {0xb45900, "SpellMouseOver"},
            {0xb45930, "SpellMouseOut"},
            {0xb45940, "SetSpell"},
        },
    });
    out.push_back(MenuCreateProfile{
        "CMerchantMenu", "0xb6ed20",
        127, 64,
        "0xb0", "0xb0", "0x12",
        {
            {"Blocker", "live"},
            {"BottomFrame", "0x40(%menu)"},
            {"TopFrame", "0x28(%menu)"},
            {"SlotGlow", "0x3448(%menu)"},
            {"Close", "live"},
            {"TabMisc", "0x3420(%menu)"},
            {"TabWeapon", "0x3410(%menu)"},
            {"TabArmor", "0x3418(%menu)"},
            {"SlotsMisc", "0x3408(%menu)"},
            {"SlotsWeapons", "0x33f8(%menu)"},
            {"SlotsArmor", "0x3400(%menu)"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
            {"TabBackpack", "0x33e0(%menu)"},
            {"TabSpell", "0x33e8(%menu)"},
            {"TabFish", "0x33f0(%menu)"},
            {"PetSlotsEquipment", "0x33c8(%menu)"},
            {"PetSlotsSpells", "0x33d0(%menu)"},
            {"PetSlotsFish", "0x33d8(%menu)"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
        },
        {
            {0xb61090, "MouseThrough"},
            {0xb68ca0, "CloseButton"},
            {0xb61040, "ItemClick"},
            {0xb688e0, "MouseOver"},
            {0xb611f0, "MouseOut"},
            {0xb610f0, "PetItemClick"},
            {0xb68530, "PetMouseOver"},
            {0xb61140, "PetMouseOut"},
        },
    });
    out.push_back(MenuCreateProfile{
        "CPetMenu", "0xb93350",
        12, 64,
        "0xa0", "0xa0", "0x12",
        {
            {"CharacterName", "0x9118(%menu)"},
            {"Level", "0x9120(%menu)"},
            {"XP", "0x9158(%menu)"},
            {"HP", "0x9150(%menu)"},
            {"Mana", "0x9148(%menu)"},
            {"MeleeDamage", "0x9128(%menu)"},
            {"RangedDamage", "0x9130(%menu)"},
            {"MagicDamage", "0x9138(%menu)"},
            {"Defense", "0x9140(%menu)"},
            {"Blocker", "live"},
            {"BottomFrame", "0x48(%menu)"},
            {"TopFrame", "0x28(%menu)"},
            {"SlotGlow", "0x9110(%menu)"},
            {"Close", "live"},
            {"PaperdollEquip", "live"},
            {"RotateLeft", "live"},
            {"RotateRight", "live"},
            {"dynamic:runtime table 0x14cc220[counter]", "live"},
            {"TabBackpack", "0x91d8(%menu)"},
            {"TabSpell", "0x91e0(%menu)"},
            {"TabFish", "0x91e8(%menu)"},
            {"SlotsEquipment", "0x91c0(%menu)"},
            {"SlotsSpells", "0x91c8(%menu)"},
            {"SlotsFish", "0x91d0(%menu)"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
        },
        {
            {0xb88850, "MouseThrough"},
            {0xb887f0, "CloseButton"},
            {0xb887a0, "ItemClick"},
            {0xb88810, "RotateLeft"},
            {0xb88820, "EndRotateLeft"},
            {0xb88830, "RotateRight"},
            {0xb88840, "EndRotateRight"},
            {0xb914d0, "MouseOver"},
            {0xb88d40, "MouseOut"},
            {0xb888b0, "SpellMouseOver"},
            {0xb888e0, "SpellMouseOut"},
            {0xb88dd0, "SetSpell"},
        },
    });
    out.push_back(MenuCreateProfile{
        "CStashMenu", "0xbfbe20",
        43, 64,
        "0xb0", "0xb0", "0x12",
        {
            {"Blocker", "live"},
            {"BottomFrame", "0x40(%menu)"},
            {"TopFrame", "0x28(%menu)"},
            {"SlotGlow", "0x3418(%menu)"},
            {"Close", "live"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
            {"TabBackpack", "0x33e0(%menu)"},
            {"TabSpell", "0x33e8(%menu)"},
            {"TabFish", "0x33f0(%menu)"},
            {"PetSlotsEquipment", "0x33c8(%menu)"},
            {"PetSlotsSpells", "0x33d0(%menu)"},
            {"PetSlotsFish", "0x33d8(%menu)"},
            {"dynamic:prefix+GetValueAsString(counter)", "live"},
        },
        {
            {0xbee470, "MouseThrough"},
            {0xbf5f90, "CloseButton"},
            {0xbee420, "ItemClick"},
            {0xbf5830, "MouseOver"},
            {0xbee710, "MouseOut"},
            {0xbee4c0, "PetItemClick"},
            {0xbf5be0, "PetMouseOver"},
            {0xbee510, "PetMouseOut"},
        },
    });
    return out;
}

} // namespace torchlight
