// GENERATED by tools/gen_menu_profiles.py --grab-only -- DO NOT EDIT.
// Source: research/batch-menu-pass.json + batch *.wiring.json
// (machine code of the pinned ELF). Grab-only createMenus: no fresh
// windows, only layout child lookups. Review against the ASM slices.
#pragma once

#include <string>
#include <vector>

namespace torchlight {

struct MenuGrabEntry {
    const char* key;
    const char* menu_field; // original field id, or "live"
};

struct MenuGrabTable {
    const char* menu_class;
    const char* address;
    std::vector<MenuGrabEntry> grabs;
};

inline std::vector<MenuGrabTable> menu_grab_tables() {
    std::vector<MenuGrabTable> out;
    out.push_back(MenuGrabTable{
        "CDialogMenu", "0xb05390",
        {
            {"Title", "0x50"},
        },
    });
    out.push_back(MenuGrabTable{
        "CDieMenu", "0xb0f540",
        {
            {"Resurrect1", "0xc8"},
            {"Resurrect2", "0xd0"},
            {"Resurrect3", "0xd8"},
            {"Choice1", "0xe0"},
            {"Choice2", "0xe8"},
            {"Choice3", "0xf0"},
            {"Title", "0x50"},
        },
    });
    out.push_back(MenuGrabTable{
        "CFishingMenu", "0xb3c270",
        {
        },
    });
    out.push_back(MenuGrabTable{
        "CInteractiveMenu", "0xb45080",
        {
        },
    });
    out.push_back(MenuGrabTable{
        "CModalMenu", "0xb7f580",
        {
            {"Decline", "0xd8"},
            {"Accept", "0xd0"},
            {"Ok", "0xc8"},
            {"Dialog", "0xe0"},
            {"Title", "0x50"},
        },
    });
    out.push_back(MenuGrabTable{
        "COptionsMenu", "0xb87ff0",
        {
            {"Title", "0x50"},
        },
    });
    out.push_back(MenuGrabTable{
        "CSettingsMenu", "0xbd6ea0",
        {
            {"Title", "0x50"},
            {"ShowTips", "0x130"},
            {"ShowFloatyNumbers", "0x138"},
            {"ShowBlood", "0x140"},
            {"NetbookMode", "0x148"},
            {"Fullscreen", "0xc8"},
            {"Antialiasing", "0xd0"},
            {"RenderBehind", "0xd8"},
            {"Rimlights", "0xe0"},
            {"HardwareSkinning", "0xe8"},
            {"VSync", "0xf0"},
            {"MusicMute", "0x120"},
            {"SoundMute", "0x128"},
            {"ResolutionDropdown", "0xf8"},
            {"ShadowDropdown", "0x100"},
            {"ParticleDropdown", "0x108"},
            {"SoundVolume", "0x118"},
            {"MusicVolume", "0x110"},
        },
    });
    out.push_back(MenuGrabTable{
        "CContinueGameMenu", "0xc404c0",
        {
            {"DeleteConfirm", "0x198"},
            {"Delete", "0x1a0"},
            {"ScrollUp", "0x170"},
            {"ScrollDown", "0x178"},
            {"Continue", "0x180"},
            {"Player1", "0xd0"},
            {"Player2", "0xd8"},
            {"Player3", "0xe0"},
            {"Player4", "0xe8"},
            {"Player5", "0xf0"},
            {"Player1Name", "0xf8"},
            {"Player2Name", "0x100"},
            {"Player3Name", "0x108"},
            {"Player4Name", "0x110"},
            {"Player5Name", "0x118"},
            {"Player1Desc", "0x120"},
            {"Player2Desc", "0x128"},
            {"Player3Desc", "0x130"},
            {"Player4Desc", "0x138"},
            {"Player5Desc", "0x140"},
            {"PlayerHighlight1", "0x148"},
            {"PlayerHighlight2", "0x150"},
            {"PlayerHighlight3", "0x158"},
            {"PlayerHighlight4", "0x160"},
            {"PlayerHighlight5", "0x168"},
            {"CharacterName", "0x188"},
            {"CharacterModsWarning", "0x190"},
        },
    });
    out.push_back(MenuGrabTable{
        "CDifficultyMenu", "0xc4a810",
        {
            {"Hardcore", "0xc8"},
        },
    });
    out.push_back(MenuGrabTable{
        "CMainMenu", "0xc52a10",
        {
            {"ContinueLast", "0xc8"},
            {"DemoVersion", "0xd0"},
            {"CharacterModsWarning", "0xd8"},
            {"Credits", "0xe0"},
            {"CreditFrame", "0xe8"},
            {"CreditFrameB", "0xf0"},
            {"CopyrightInfo", "live"},
        },
    });
    out.push_back(MenuGrabTable{
        "CNewGameMenu", "0xc5d730",
        {
            {"CreatePlayer", "0xc8"},
            {"EditBox", "0xd0"},
            {"EditBoxPet", "0xd8"},
            {"CharacterClass", "0xe0"},
            {"CharacterClassDescription", "0xe8"},
            {"Back", "0xf0"},
        },
    });
    out.push_back(MenuGrabTable{
        "CTipMenu", "0xe4c800",
        {
            {"Ok", "0xc0"},
            {"Dialog", "0xc8"},
            {"Title", "0x50"},
            {"ShowTips", "0xd0"},
        },
    });
    out.push_back(MenuGrabTable{
        "CCinematicMenu", "0xe9b180",
        {
            {"Skip", "0xc0"},
            {"DialogText", "0xc8"},
            {"Background", "0xd0"},
        },
    });
    out.push_back(MenuGrabTable{
        "CWaypointMenu", "0xea58b0",
        {
            {"dynamic:Button+GetValueAsString(counter)", "0xc8"},
            {"dynamic:Choice+GetValueAsString(counter)", "0x258"},
            {"Title", "live"},
        },
    });
    return out;
}

} // namespace torchlight
