#!/usr/bin/env python3
"""Generate the MenuCreateProfile table from the batch-menu pass report.

Single source: research/batch-menu-pass.json plus the per-function
*.wiring.json files it was built from. Review the emitted header against
the ASM slices before committing: generator output is a mechanical
transcription, not a proof.

Usage:
  python3 tools/gen_menu_profiles.py --classes CInventoryMenu,CMerchantMenu,CPetMenu,CStashMenu
      --out include/torchlight/menu_create_profiles.hpp
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def short_handler(symbol):
    # 'CMerchantMenu::handle_PetItemClick(CEGUI::EventArgs const&)' -> 'PetItemClick'
    name = symbol.split("(")[0]
    name = name.split("::")[-1]
    return name[len("handle_"):] if name.startswith("handle_") else name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--classes", default="CInventoryMenu,CMerchantMenu,CPetMenu,CStashMenu")
    ap.add_argument("--report", default=os.path.join(HERE, "research", "batch-menu-pass.json"))
    ap.add_argument("--batch-dir", default=os.path.join(HERE, "research", "disassembly", "batch"))
    ap.add_argument("--out", default=os.path.join(HERE, "include", "torchlight", "menu_create_profiles.hpp"))
    args = ap.parse_args()

    report = json.load(open(args.report, encoding="utf-8"))
    wanted = args.classes.split(",")
    profiles = []
    for f in report["functions"]:
        if f["method"] != "createMenus" or f["class"] not in wanted:
            continue
        addr = f["address"]
        wpath = None
        for fn in os.listdir(args.batch_dir):
            if fn.startswith(addr[2:] + "-") and fn.endswith(".wiring.json"):
                wpath = os.path.join(args.batch_dir, fn)
                break
        if wpath is None:
            raise SystemExit("no wiring json for %s" % addr)
        w = json.load(open(wpath, encoding="utf-8"))
        loops = sorted(w.get("counter_loops", []), key=lambda c: c["inc_line"])
        bounds = [c.get("bound") for c in loops]
        backs = [b["base"] for b in sorted(w.get("back_pointers", []),
                                           key=lambda b: b["line"])]
        idxoffs = sorted(set(o["add"] for o in w.get("index_offsets", [])))
        handlers = []
        for s in w.get("subscriptions", []):
            h = (s["handler"], short_handler(s["symbol"]))
            if h not in handlers:
                handlers.append(h)
        grabs = [(s["key"] or ("dynamic:" + (s["dynamic"] or "?")), s["menu_store"])
                 for s in w.get("child_searches", [])]
        profiles.append({
            "class": f["class"], "address": addr,
            "table_bound": bounds[0] if len(bounds) > 0 else None,
            "slot_bound": bounds[1] if len(bounds) > 1 else None,
            "table_base": backs[0] if len(backs) > 0 else None,
            "slot_base": backs[1] if len(backs) > 1 else (backs[0] if backs else None),
            "index_offsets": idxoffs,
            "handlers": handlers,
            "grabs": grabs,
        })

    missing = set(wanted) - {p["class"] for p in profiles}
    if missing:
        raise SystemExit("missing classes: %s" % sorted(missing))

    L = []
    L.append("// GENERATED by tools/gen_menu_profiles.py -- DO NOT EDIT.")
    L.append("// Source: research/batch-menu-pass.json + batch *.wiring.json")
    L.append("// (machine code of the pinned ELF). Review against the ASM")
    L.append("// slices before use; see research/inventory-open.md.")
    L.append("#pragma once")
    L.append("")
    L.append("#include <cstdint>")
    L.append("#include <string>")
    L.append("#include <utility>")
    L.append("#include <vector>")
    L.append("")
    L.append("namespace torchlight {")
    L.append("")
    L.append("struct MenuGrab {")
    L.append("    const char* key;")
    L.append("    const char* menu_field; // original CInventoryMenu-style field id, or \"live\"")
    L.append("};")
    L.append("")
    L.append("struct MenuHandler {")
    L.append("    std::uint32_t id; // original handler code address")
    L.append("    const char* name;")
    L.append("};")
    L.append("")
    L.append("struct MenuCreateProfile {")
    L.append("    const char* menu_class;")
    L.append("    const char* address;")
    L.append("    unsigned table_loop_bound;")
    L.append("    unsigned slot_loop_bound;")
    L.append("    const char* table_array_base;")
    L.append("    const char* slot_array_base;")
    L.append("    const char* index_offset;")
    L.append("    std::vector<MenuGrab> grabs;")
    L.append("    std::vector<MenuHandler> handlers;")
    L.append("};")
    L.append("")
    L.append("inline std::vector<MenuCreateProfile> menu_create_profiles() {")
    L.append("    std::vector<MenuCreateProfile> out;")
    for p in sorted(profiles, key=lambda p: p["class"]):
        L.append("    out.push_back(MenuCreateProfile{")
        L.append('        "%s", "%s",' % (p["class"], p["address"]))
        L.append("        %s, %s," % (p["table_bound"], p["slot_bound"]))
        L.append('        "%s", "%s", "%s",' % (
            p["table_base"], p["slot_base"],
            p["index_offsets"][0] if p["index_offsets"] else "?"))
        L.append("        {")
        for key, store in p["grabs"]:
            field = store.replace("(%rbx)", "") if store != "?" else "live"
            L.append('            {"%s", "%s"},' % (key, field))
        L.append("        },")
        L.append("        {")
        for hid, hname in p["handlers"]:
            L.append('            {%s, "%s"},' % (hid, hname))
        L.append("        },")
        L.append("    });")
    L.append("    return out;")
    L.append("}")
    L.append("")
    L.append("} // namespace torchlight")
    L.append("")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("wrote %s (%d profiles)" % (args.out, len(profiles)))


if __name__ == "__main__":
    main()
