#!/usr/bin/env python3
"""Generate the MenuCreateProfile table from the batch-menu pass report.

Single source: research/batch-menu-pass.json plus the per-function
*.wiring.json files it was built from. Review the emitted header against
the ASM slices before committing: generator output is a mechanical
transcription, not a proof.

Usage:
  python3 tools/gen_menu_profiles.py --classes CInventoryMenu,CMerchantMenu,CPetMenu,CStashMenu
      --out include/torchlight/menu_create_profiles.hpp
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def short_handler(symbol):
    # 'CMerchantMenu::handle_PetItemClick(CEGUI::EventArgs const&)' -> 'PetItemClick'
    name = symbol.split("(")[0]
    name = name.split("::")[-1]
    return name[len("handle_"):] if name.startswith("handle_") else name


def emit_grabs(args):
    report = json.load(open(args.report, encoding="utf-8"))
    tables = []
    for f in sorted(report["functions"], key=lambda f: f["address"]):
        if f["method"] != "createMenus" or f.get("creates", -1) != 0:
            continue
        addr = f["address"]
        wpath = None
        for fn in os.listdir(args.batch_dir):
            if fn.startswith(addr[2:] + "-") and fn.endswith(".wiring.json"):
                wpath = os.path.join(args.batch_dir, fn)
                break
        grabs = []
        if wpath is not None:
            w = json.load(open(wpath, encoding="utf-8"))
            for s in w.get("child_searches", []):
                key = s["key"] or ("dynamic:" + (s["dynamic"] or "?"))
                store = s["menu_store"]
                field = store.replace("(%menu)", "") if store != "?" else "live"
                grabs.append((key, field))
        tables.append({"class": f["class"], "address": addr, "grabs": grabs})
    L = []
    L.append("// GENERATED by tools/gen_menu_profiles.py --grab-only -- DO NOT EDIT.")
    L.append("// Source: research/batch-menu-pass.json + batch *.wiring.json")
    L.append("// (machine code of the pinned ELF). Grab-only createMenus: no fresh")
    L.append("// windows, only layout child lookups. Review against the ASM slices.")
    L.append("#pragma once")
    L.append("")
    L.append("#include <string>")
    L.append("#include <vector>")
    L.append("")
    L.append("namespace torchlight {")
    L.append("")
    L.append("struct MenuGrabEntry {")
    L.append("    const char* key;")
    L.append("    const char* menu_field; // original field id, or \"live\"")
    L.append("};")
    L.append("")
    L.append("struct MenuGrabTable {")
    L.append("    const char* menu_class;")
    L.append("    const char* address;")
    L.append("    std::vector<MenuGrabEntry> grabs;")
    L.append("};")
    L.append("")
    L.append("inline std::vector<MenuGrabTable> menu_grab_tables() {")
    L.append("    std::vector<MenuGrabTable> out;")
    for t in tables:
        L.append("    out.push_back(MenuGrabTable{")
        L.append('        "%s", "%s",' % (t["class"], t["address"]))
        L.append("        {")
        for key, field in t["grabs"]:
            L.append('            {"%s", "%s"},' % (key, field))
        L.append("        },")
        L.append("    });")
    L.append("    return out;")
    L.append("}")
    L.append("")
    L.append("} // namespace torchlight")
    L.append("")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("wrote %s (%d tables)" % (args.out, len(tables)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--classes", default="CInventoryMenu,CMerchantMenu,CPetMenu,CStashMenu,CCombineMenu,CEnchantMenu,CQuestMenu,CQuestDialogMenu,CSkillMenu,CJournalMenu")
    ap.add_argument("--loops", default=os.path.join(HERE, "research", "menu-key-loops.json"))
    ap.add_argument("--report", default=os.path.join(HERE, "research", "batch-menu-pass.json"))
    ap.add_argument("--batch-dir", default=os.path.join(HERE, "research", "disassembly", "batch"))
    ap.add_argument("--out", default=os.path.join(HERE, "include", "torchlight", "menu_create_profiles.hpp"))
    ap.add_argument("--grab-only", action="store_true",
                    help="emit MenuGrabTable for createMenus with no fresh windows instead")
    args = ap.parse_args()

    if args.grab_only:
        emit_grabs(args)
        return

    report = json.load(open(args.report, encoding="utf-8"))
    loops_by_class = {}
    profile_scalars = {}
    try:
        with open(args.loops, encoding="utf-8") as fh:
            sidecar = json.load(fh)
            for entry in sidecar.get("loops", []):
                loops_by_class.setdefault(entry["menu"], []).append(entry)
            profile_scalars = sidecar.get("profile_scalars", {})
    except OSError:
        pass
    wanted = args.classes.split(",")
    profiles = []
    for f in report["functions"]:
        if f["method"] != "createMenus" or f["class"] not in wanted:
            continue
        addr = f["address"]
        wpath = None
        for fn in os.listdir(args.batch_dir):
            if fn.startswith(addr[2:] + "-") and fn.endswith(".wiring.json"):
                wpath = os.path.join(args.batch_dir, fn)
                break
        if wpath is None:
            raise SystemExit("no wiring json for %s" % addr)
        w = json.load(open(wpath, encoding="utf-8"))
        loops = sorted(w.get("counter_loops", []),
                       key=lambda c: (c["inc_line"] is None, c["inc_line"] or 0))
        bounds = [c.get("bound") for c in loops]
        backs = [b["base"] for b in sorted(w.get("back_pointers", []),
                                           key=lambda b: b["line"])]
        idxoffs = sorted(set(o["add"] for o in w.get("index_offsets", [])))
        handlers = []
        for s in w.get("subscriptions", []):
            h = (s["handler"], short_handler(s["symbol"]))
            if h not in handlers:
                handlers.append(h)
        grabs = [(s["key"] or ("dynamic:" + (s["dynamic"] or "?")), s["menu_store"])
                 for s in w.get("child_searches", [])]
        scalars = profile_scalars.get(f["class"], {})
        bounds = scalars.get("bounds", [0, 0])
        profiles.append({
            "class": f["class"], "address": addr,
            "table_bound": bounds[0], "slot_bound": bounds[1],
            "table_base": backs[0] if len(backs) > 0 else None,
            "slot_base": backs[1] if len(backs) > 1 else (backs[0] if backs else None),
            "index_offset": scalars.get("index_offset", "none"),
            "handlers": handlers,
            "grabs": grabs,
            "loops": loops_by_class.get(f["class"], []),
        })

    missing = set(wanted) - {p["class"] for p in profiles}
    if missing:
        raise SystemExit("missing classes: %s" % sorted(missing))

    L = []
    L.append("// GENERATED by tools/gen_menu_profiles.py -- DO NOT EDIT.")
    L.append("// Source: research/batch-menu-pass.json + batch *.wiring.json")
    L.append("// (machine code of the pinned ELF). Review against the ASM")
    L.append("// slices before use; see research/inventory-open.md.")
    L.append("#pragma once")
    L.append("")
    L.append("#include <cstdint>")
    L.append("#include <string>")
    L.append("#include <utility>")
    L.append("#include <vector>")
    L.append("")
    L.append("namespace torchlight {")
    L.append("")
    L.append("struct MenuGrab {")
    L.append("    const char* key;")
    L.append("    const char* menu_field; // original CInventoryMenu-style field id, or \"live\"")
    L.append("};")
    L.append("")
    L.append("struct MenuHandler {")
    L.append("    std::uint32_t id; // original handler code address")
    L.append("    const char* name;")
    L.append("};")
    L.append("")
    L.append("struct MenuKeyLoop {")
    L.append("    const char* keys; // comma-joined prefixes, or table:0x... for runtime names")
    L.append("    unsigned first;")
    L.append("    unsigned last;")
    L.append("    const char* back_base; // window+0x1d8 base, or \"none\"")
    L.append("    const char* back_offset; // index offset, or \"none\"")
    L.append("};")
    L.append("")
    L.append("struct MenuCreateProfile {")
    L.append("    const char* menu_class;")
    L.append("    const char* address;")
    L.append("    unsigned table_loop_bound;")
    L.append("    unsigned slot_loop_bound;")
    L.append("    const char* table_array_base;")
    L.append("    const char* slot_array_base;")
    L.append("    const char* index_offset;")
    L.append("    std::vector<MenuGrab> grabs;")
    L.append("    std::vector<MenuHandler> handlers;")
    L.append("    std::vector<MenuKeyLoop> loops;")
    L.append("};")
    L.append("")
    L.append("inline std::vector<MenuCreateProfile> menu_create_profiles() {")
    L.append("    std::vector<MenuCreateProfile> out;")
    for p in sorted(profiles, key=lambda p: p["class"]):
        L.append("    out.push_back(MenuCreateProfile{")
        L.append('        "%s", "%s",' % (p["class"], p["address"]))
        L.append("        %s, %s," % (p["table_bound"], p["slot_bound"]))
        L.append('        "%s", "%s", "%s",' % (
            p["table_base"] or "none", p["slot_base"] or "none",
            p["index_offset"]))
        L.append("        {")
        for key, store in p["grabs"]:
            field = store.replace("(%menu)", "") if store != "?" else "live"
            L.append('            {"%s", "%s"},' % (key, field))
        L.append("        },")
        L.append("        {")
        for hid, hname in p["handlers"]:
            L.append('            {%s, "%s"},' % (hid, hname))
        L.append("        },")
        L.append("        {")
        for lp in p["loops"]:
            base = '"%s"' % lp["back_base"] if lp["back_base"] else '"none"'
            off = '"%s"' % lp["back_offset"] if lp["back_offset"] else '"none"'
            L.append('            {"%s", %d, %d, %s, %s},' % (
                ",".join(lp["keys"]), lp["first"], lp["last"], base, off))
        L.append("        },")
        L.append("    });")
    L.append("    return out;")
    L.append("}")
    L.append("")
    L.append("} // namespace torchlight")
    L.append("")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("wrote %s (%d profiles)" % (args.out, len(profiles)))


if __name__ == "__main__":
    main()
