#include "torchlight/ui_function_bindings.hpp"
#include "torchlight/recovered/ui_bindings.hpp"

namespace torchlight {
// original-code: table @0x14b7dc0 and mapToFunctions @0xa980e0.
// Reviewed adapter is generated by CMake; see research/recovery-automation.md.
const UiFunctionNames& ui_function_names() noexcept { return recovered::command_names; }

std::string_view ui_function_name(UiLayoutFunction value) noexcept {
    const int index = static_cast<int>(value);
    const auto& names = recovered::command_names;
    return index >= 0 && index < static_cast<int>(names.size()) ? names[index] : std::string_view{};
}

void map_ui_functions(UiFunctionTree& tree, UiFunctionTree::Node root, const UiFunctionNames& names) {
    recovered::map_functions(tree, root, names);
}
} // namespace torchlight
